/**
 * IMPORTED PROBLEMS — human-authored, openly licensed, not generated.
 *
 * Generated by scripts/import-openstax.mjs. DO NOT EDIT BY HAND and do not
 * paste its contents anywhere a learner might read them: the whole value of
 * these items is that the answers have not been seen. Regenerate instead.
 *
 * Source: Statistics by OpenStax, CC BY 4.0
 *   https://openstax.org/details/books/statistics
 * Adapted: problem text taken verbatim; answers taken from the book's own
 * solutions; skill tags, difficulty and answer tolerances added by this app.
 * See ATTRIBUTIONS.md.
 *
 * Only exercises whose printed solution is a BARE NUMBER are imported, which
 * is a small fraction of the book. That is the subset where a misaligned
 * parse can be detected, and a wrong answer key on an app built to keep an
 * honest record is worse than having less content.
 *
 * Difficulty is a flat 3 — the source does not grade its exercises, and
 * inventing a spread would be a number with nothing behind it.
 */
import type { ItemTemplate } from '../../domain/types'
import { tpl } from '../lib'

const SOURCE = {
  title: "Statistics",
  author: "OpenStax",
  licence: 'CC BY 4.0' as const,
  url: "https://openstax.org/details/books/statistics",
  adapted: true,
}

interface Imported {
  id: string
  prompt: string
  answer: number
  tolerance: number
  skill: string
  bucket: ItemTemplate['bucket']
}

const ITEMS: Imported[] = [
  {
    "id": "os-stat-1",
    "prompt": "Second quartile = median = 50 th percentile = ________",
    "answer": 4,
    "tolerance": 0.5,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-2",
    "prompt": "Find the probability that a Health Index Score is 81.0.",
    "answer": 0,
    "tolerance": 0.5,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-3",
    "prompt": "According to a recent article the average number of babies born with significant hearing loss (deafness) is approximately two per 1,000 babies in a healthy baby nursery. The number climbs to an average of 30 per 1,000 babies in an intensive care nursery. Suppose that 1,000 babies from healthy baby nurseries were randomly surveyed. Find the probability that exactly two babies were born deaf.",
    "answer": 0.2709,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-4",
    "prompt": "What is the probability that the store will have more than 12 customers in the first hour?",
    "answer": 0.2084,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-5",
    "prompt": "Find the probability that a randomly selected home has more than 3,000 square feet given that you already know the house has more than 2,000 square feet.",
    "answer": 0.6,
    "tolerance": 0.05,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-6",
    "prompt": "A normal distribution has a mean of 61 and a standard deviation of 15. What is the median?",
    "answer": 61,
    "tolerance": 0.5,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-7",
    "prompt": "X ~ N (6, 2) Find the probability that x is between three and nine.",
    "answer": 0.8664,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-8",
    "prompt": "X ~ N (–3, 4) Find the probability that x is between one and four.",
    "answer": 0.1186,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-9",
    "prompt": "An unknown distribution has a mean of 45 and a standard deviation of 8. A sample size of 50 is drawn randomly from the population. Find the probability that the sum of the 50 values is more than 2,400.",
    "answer": 0.004,
    "tolerance": 0.00005,
    "skill": "m-sampling",
    "bucket": "math"
  },
  {
    "id": "os-stat-10",
    "prompt": "Find the probability that the sum of the 95 values is greater than 7,650.",
    "answer": 0.3345,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-11",
    "prompt": "Find the probability that the sum of the 95 values is less than 7,400.",
    "answer": 0.0436,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-12",
    "prompt": "Find the sum that is 1.5 standard deviations below the mean of the sums.",
    "answer": 7424.56,
    "tolerance": 0.005,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-13",
    "prompt": "Find the probability that the sum of the 40 values is greater than 7,500.",
    "answer": 0.0089,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-14",
    "prompt": "Find the probability that the sum of the 40 values is less than 7,000.",
    "answer": 0.0569,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-15",
    "prompt": "Find the probability that the sum of the 100 values is greater than 3,910.",
    "answer": 0.0359,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-16",
    "prompt": "Find the probability that the sum of the 100 values is less than 3,900.",
    "answer": 0.4207,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-17",
    "prompt": "Find the probability that the sum of the 100 values falls between the numbers you found in (16) and (17).",
    "answer": 0.5433,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-18",
    "prompt": "Find the probability that the sums will fall between the z -scores –2 and 1.",
    "answer": 0.8186,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-19",
    "prompt": "An unknown distribution has a mean of 25 and a standard deviation of six. Let X = one object from this distribution. What is the sample size if the standard deviation of ΣX is 42?",
    "answer": 49,
    "tolerance": 0.5,
    "skill": "m-sampling",
    "bucket": "math"
  },
  {
    "id": "os-stat-20",
    "prompt": "An unknown distribution has a mean of 19 and a standard deviation of 20. Let X = the object of interest. What is the sample size if the mean of ΣX is 15,200?",
    "answer": 800,
    "tolerance": 0.5,
    "skill": "m-sampling",
    "bucket": "math"
  },
  {
    "id": "os-stat-21",
    "prompt": "Find the probability that the mean actual weight for the 100 weights is greater than 25.2.",
    "answer": 0.0003,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-22",
    "prompt": "Find the 90 th percentile for the mean weight for the 100 weights.",
    "answer": 25.07,
    "tolerance": 0.005,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-23",
    "prompt": "Find the 90 th percentile for the total weight of the 100 weights.",
    "answer": 2507.4,
    "tolerance": 0.005,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-24",
    "prompt": "Find the probability that the sample mean is between 7 and 11.",
    "answer": 0.7799,
    "tolerance": 0.00005,
    "skill": "m-prob",
    "bucket": "math"
  },
  {
    "id": "os-stat-25",
    "prompt": "Find the 80 th percentile for the total length of time 64 batteries last.",
    "answer": 707.3,
    "tolerance": 0.05,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-26",
    "prompt": "Find the interquartile range (IQR) for the mean amount of time 64 batteries last.",
    "answer": 1.69,
    "tolerance": 0.005,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-27",
    "prompt": "The power of a test is 0.981. What is the probability of a Type II error?",
    "answer": 0.019,
    "tolerance": 0.0005,
    "skill": "s-hypo",
    "bucket": "science"
  },
  {
    "id": "os-stat-28",
    "prompt": "A microbiologist is testing a water sample for E. coli. Suppose the null hypothesis, H 0 , is the sample does not contain E. coli. The probability that the sample does not contain E. coli, but the microbiologist thinks it does is 0.012. The probability that the sample does contain E. coli, but the microbiologist thinks it does not is 0.002. What is the power of this test?",
    "answer": 0.998,
    "tolerance": 0.0005,
    "skill": "s-hypo",
    "bucket": "science"
  },
  {
    "id": "os-stat-29",
    "prompt": "A sample standard deviation of 15 minutes is the same as a sample variance of __________ minutes.",
    "answer": 225,
    "tolerance": 0.5,
    "skill": "m-variability",
    "bucket": "math"
  },
  {
    "id": "os-stat-30",
    "prompt": "Data are collected on the relationship between the number of hours per week practicing a musical instrument and scores on a math test. The line of best fit is as follows: ŷ = 72.5 + 2.8 x. What would you predict the score on a math test will be for a student who practices a musical instrument for five hours a week?",
    "answer": 86.5,
    "tolerance": 0.05,
    "skill": "s-corr",
    "bucket": "science"
  }
]

export const IMPORTED_TEMPLATES: ItemTemplate[] = ITEMS.map((it) =>
  tpl(
    {
      id: it.id,
      name: 'Imported exercise',
      skillIds: [it.skill],
      bucket: it.bucket,
      difficulty: 3,
      variants: 1,
      minutes: 2.5,
      source: SOURCE,
      provenance: `${SOURCE.title} by ${SOURCE.author} (${SOURCE.licence}). Problem text verbatim; tags and tolerance added here.`,
    },
    () => ({
      title: 'From a textbook',
      prompt: it.prompt,
      answer: { type: 'numeric', answer: it.answer, tolerance: it.tolerance },
      hints: [
        'Read it once for what is being asked, then once for the numbers.',
        'Name the quantity you need before computing anything.',
      ],
      explanation: `The answer is **${it.answer}**. This problem was written by people making a textbook, not generated from a pattern, so the wording will not match the shapes the rest of this app uses — which is the point of having it.`,
    }),
  ),
)
