/**
 * The update log. Every shipped build gets its story told here — what
 * changed and why it serves learning. Shown in Settings → About.
 */
export interface ChangelogEntry {
  version: string
  date: string
  title: string
  points: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '7.7',
    date: '2026-08-09',
    title: 'Every Topic Now Has A Way In, And The Guardian Path Stopped Rewarding Suspicion',
    points: [
      'The 30 remaining topics that started at a hard level now have a gentle first question each — reading a scatter for direction, what a logarithm asks, checking whether a pair of numbers fits both equations, tracing two lines of code by hand, spotting the control group, rounding to the nearest power of ten, and more. Zero topics now start hard, down from 44, and easy questions went from 6% of the bank to 11%.',
      'The Guardian and Observer paths had a real problem: out of 55 question types, exactly ONE ever had "nothing is wrong here" as the right answer. Answering "that\'s suspicious" every single time would have scored nearly full marks. That is not influence defence — a person trained to read every direct request as manipulation has been given a different problem, not protected from one. Three new question types are now about half ordinary cases: a real deadline stated plainly, someone genuinely disappointed, two accounts that differ without contradicting. Getting those right is half the skill.',
      'The answer checker could be fooled by things that are not answers. Certain odd text coerced into "you picked the first option" on 180 question types, and a bare comma could actually SCORE a multi-select. You could not do this by tapping — it needed input the app never sends — but the checker is the last thing between you and a false claim about what you know, so it now only accepts plain option numbers.',
      'Tap "Challenge" as a new learner and you used to get an ordinary session with no explanation, because there was nothing near your ceiling yet. Now it tells you what was missing and why it is running something else instead.',
      'The spatial puzzle could always be played by keyboard — arrows move, R rotates, Enter places — and said so nowhere. Now it says so, once you have picked up a piece.',
      'Also checked and found fine, rather than assumed: 16 kinds of corrupted saved session (all safely refused, nothing lost, no crash), 17 kinds of malformed import file, a full or blocked browser storage, the app at 320px wide, dark mode, and screen-reader roles on the chess board and logic grids.',
      'Still honest about the gaps: the easy end of the question bank is thinner than the hard end, the review pile settles around 40 rather than emptying, and three hunts have each found real bugs the previous one missed — so a fourth probably would too. What changed is that every kind of bug found so far now has a release check guarding it.',
    ],
  },
  {
    version: '7.6',
    date: '2026-08-09',
    title: 'A Ten-Minute Session Was Fifteen Minutes, And The Difficulty Dial Was Stuck',
    points: [
      'If you picked a 10-minute session you were given about 15, on 99% of days. Three separate counting mistakes: the maths for a short session forgot to leave room for one of its own blocks (a comment right next to it even claimed it did), the warm-up checked whether it had room BEFORE adding a question so it always overshot by one, and the "explain it back" ending is a 4-minute task that was chosen after everything else had already been sized as if it were 2. Now a 10-minute session is 10 minutes. This matters most for the person who picked 10 because 10 is all they had.',
      'That oversized ending was also why Meta Lab was eating 14% of a short session against its 5% share, and why one single question type was 8% of a whole year of practice for anyone doing short sessions. Both back to normal.',
      'The bigger one: when you were struggling, the app knew and could not act on it. It reads your recent accuracy and asks for easier work — and it was asking, at full strength, every month for a simulated year, while the difficulty it actually served went UP. A learner getting 14-19% right sat there all year. Two reasons: the question chooser was tuned to prefer slightly-harder work (right when you are coping, wrong when you are drowning) and a brand-new question could outbid an appropriate one on novelty alone. Now the preference flips while you are struggling.',
      'And the other half of that: 44 of 122 topics had no easy way in — the gentlest question they offered was already a "combine ideas without help" problem, and 14 topics started at "advanced". So the app could ask for easier work and there was none to give. Fourteen new foundation questions open those doors: reading a two-way table, what a fractional exponent means, which side of a triangle is which, what a logarithm is asking, naming the parts of a circle, why removing your own options can win an argument. A release check now refuses to ship a topic with no way in.',
      'Reviews were piling up faster than they could ever be cleared — for every ability level, including the strongest, the "due" number climbed all year. The warm-up served about two reviews a session no matter how many were waiting, while the number waiting grows with every skill you master. It now widens when the queue is long (up to about a third of the session, never more — urgent work is not allowed to take over). Reviews done over a year went from 643 to 1,095 and the pile stopped growing.',
      'Honest about what is still not fixed: 30 topics still start at a "combine ideas" level rather than a gentle one, and only 6% of all questions are foundation-level, so a struggling learner still has less easy material than they should. And the review pile is stable now, not empty — around 40 once you own a lot of skills.',
    ],
  },
  {
    version: '7.5',
    date: '2026-08-09',
    title: 'The Frontier Stopped Moving For Learners Doing Well',
    points: [
      'The worst bug this app has had, and it punished you for doing well. Simulated over a year at high accuracy, a learner reached only 58 of 122 skills — and spent 215 of 365 daily focus blocks on "Integers, factors & the number line", the very first skill in the tree, long after they had mastered it. Two causes. A skill kept claiming credit for "unlocking" the skills after it even once you already owned it and nothing was waiting on it any more, so the root of the tree out-scored everything forever. And three skills had fewer question types than the app\'s own rule requires to call something Independent, so they could never graduate off the frontier and kept their priority permanently. After the fix: 120 of 122 skills reached, 119 owned instead of 34, and no single skill takes more than a sixth of your focus blocks.',
      'The reason you were told for a choice is now true as well. "4 skills are waiting on it" used to be printed for a skill that exactly 1 was waiting on.',
      'The coach can finally name what keeps going wrong. It sorts your mistakes by CAUSE — a slip is a different problem from a gap and needs a different fix — but it could only work that out from 4% of your mistakes, so it said "not enough yet" forever unless you tagged every error by hand. It now reads the cause from what you actually did: which step of a chain broke, which specific wrong answer you picked, or how the repair went (fixing it yourself reads as a slip; needing the explanation reads as a gap). That is 51% of mistakes, and it deliberately stays silent on multiple choice, where a lucky second guess would look like knowing.',
      'Case files, work studios and the method drill used to throw away every cause they diagnosed. They now carry the first checkpoint that broke.',
      'Data interpretation promised "tables, bar charts, line graphs, and scatter plots" and shipped one table question. It now has bar charts, line graphs, and choosing the right display for a question. Chart defence gained two questions that make you recompute the honest number a truncated axis or a cherry-picked window is hiding, instead of picking the sceptical-sounding option. Forecasting gained Brier scoring — the app has always computed it for your forecasts and never taught what it means.',
      'Physics was the thinnest subject in the app and almost every question was "put the numbers in the formula". Six new kinds, built on a published physics-teaching taxonomy of tasks that cannot be answered by substitution: rank four carts by momentum, spot what is wrong with a calculation (and sometimes nothing is), match a position table to the motion it describes, work backwards from the answer, judge which of two students arguing is right, and find the one broken link in an estimate.',
      'Two new release gates so none of this can quietly come back: every skill must be able to reach Independent through ordinary daily practice, and a simulated year must still cover most of the curriculum without parking on one topic.',
      'The research ledger gained a large landscape review and, more importantly, five corrections to claims already in it — including that spacing has NOT been shown to help for mathematical procedures specifically, that Bloom\'s famous "two sigma" does not survive scrutiny, and that immediate feedback has no measured advantage over feedback a few days later.',
    ],
  },
  {
    version: '7.4',
    date: '2026-08-09',
    title: 'Reviewing The Merge: Two Real Bugs In The Engine',
    points: [
      'The California work checks out — the standard codes match the official ones exactly, and the new alignment check is a genuine release gate rather than menu copy. Two existing checks were also made stricter in the process, not looser.',
      'Bug in the new speed-up for your history: it now remembers past work instead of recalculating from scratch every time, but it decided whether that memory still applied by checking only the LAST item. Two different histories can end with the same item and differ earlier, so it could answer from the wrong past. A side-by-side test caught it reporting zero recent misses where a full recalculation said one. It now verifies the whole history, which costs microseconds.',
      'The physics-starvation bug came back on the new grade-8 course: the course priority stacked on top of maths\' default priority and out-muscled the fix, so physics went to 0% again. Maths now stands down entirely while another subject is starving.',
      'Fixing that exposed a third layer underneath. Physics has one skill needing no prerequisites, and it was quietly filling physics\' MINUTES while the other ten skills stayed locked — so a learner could do the same physics topic for a year and the app would think physics was healthy. Priority now looks at how much of a subject is still locked, not just how many minutes it got.',
      'The starvation test now simulates every course rather than only the no-course case, which is exactly why this was caught instead of shipped.',
    ],
  },
  {
    version: '7.3',
    date: '2026-08-09',
    title: 'The Math Courses Now Have A California Floor',
    points: [
      'The normal course ladder no longer skips two entire California courses. Math 7 now leads to Math 8, then a full high-school Algebra I course, Geometry, and Algebra II. Math 7+ still leads to accelerated Algebra I for a learner who is genuinely ready; acceleration is an option, not the default route.',
      'The actual question bank—not just the course names—was checked against California’s official Grade 6, Grade 7, Grade 8, Algebra I, Geometry, and Algebra II standards and the 2023 Mathematics Framework. Twenty-one explicit skills and 37 original generated question families fill the missing work: early inequalities and variable relationships; geometric construction and slicing; piecewise functions, residuals, and standard deviation; congruence and circle/coordinate proofs; conditional probability; complex numbers; polynomial division; rational and radical equations; logarithms; unit-circle trigonometry; conics; and statistical inference.',
      'Difficulty starts in the right place. Sixth-grade integer ideas are now separate from seventh-grade signed-number operations, while percent, unit conversion, coordinate work, expressions, first equations, and simple inequalities begin where California places them. No old problem was thrown away: later-level signed-operation questions remain in ordinary adaptive practice under their correct Grade 7 skill.',
      'A new release gate treats California coverage as the minimum floor. Every official topic cluster must be present in its course, every mapped skill must have normal-flow questions, every cluster needs an approachable entry task, and every cluster must reach the course’s intended challenge level. Extra useful and advanced material is still allowed.',
      'Course selection now shows the California standards label and a plain-language topic summary, so choosing “Math 8” or “Geometry” says what the course actually contains instead of asking you to trust a short name.',
    ],
  },
  {
    version: '7.2',
    date: '2026-08-09',
    title: 'Every Question Gets A Fair Route Into Today',
    points: [
      'Today no longer lets a fixed tie-break quietly favor the same question families forever. Normal questions rotate when they are near the right difficulty: unseen families get a turn, recent repeats step back, and older work returns. Projects still get a proper whole application day, and one-time readiness probes stay rare, because “everything can appear” should not mean “anything appears randomly.” A release audit now proves every built-in question has an explicit Today route and every ordinary family can win its turn.',
      'Two skills could never reach Independent no matter how well you answered: Physics Estimation and Choosing a Method each had only one question family, while the evidence rule requires two. Both now have a genuinely different second family, the release gate checks the real family requirement used by the evidence engine, and every skill page tells you plainly what proof is needed next—including when the honest ceiling is Retained because no sufficiently different transfer task exists yet.',
      'Saving is harder to lose and easier to inspect. A corrupt main save now falls back to the backup or mirror instead of silently starting over; each attempt also enters an append-only recovery journal; completed sessions are written before their resumable draft is cleared; double taps and resumed finishes cannot duplicate attempts or sessions; and sample mode refuses to switch unless your real data was safely stashed. Settings now shows live-save, checkpoint, journal, recovery-source, and sample-stash health.',
      'Large histories now extend the existing evidence calculation with only new attempts instead of replaying the whole log after every answer. Session navigation and draft validation moved into tested, versioned pure logic, malformed resume positions are rejected safely, and forecast probabilities can finally be revised from the Coach while keeping the revision history the data model already stored.',
      'The test runner is pinned to this worktree so hidden developer scratch copies no longer run twice. The curriculum is split into smaller math, STEM, Path, puzzle, meta, and authentic-work cache boundaries, and a mobile Chromium smoke test now checks the five-tab shell, daily-session launch, console errors, and horizontal overflow before deployment.',
    ],
  },
  {
    version: '7.1',
    date: '2026-08-09',
    title: 'Physics Was Quietly Getting 1% Of Your Time',
    points: [
      'The big one, and it was invisible: every physics skill sits behind a maths prerequisite, and the block that could have taught physics was handed to maths before physics was ever considered. Simulated over a year, physics got 1-2% of practice against the 8% it was promised — and the single skill unlocking the whole physics tree had never once been scheduled. Nothing looked wrong: the balance card showed "Physics 8% / 0%" like an ordinary shortfall, and every test passed. Now a skill that is blocking a whole subject gets priority and says so, any subject falling badly behind takes the lead slot, and the worst gap across every subject dropped from 8 points to 3.',
      'A related one it uncovered: when the placement test judges you strong across a whole subject, every skill in that subject was being pushed DOWN equally — which reorders nothing and just makes the whole subject lose out. Fixed, so a strong diagnostic no longer quietly steers you away from the subject you are good at.',
      '"Send to another device" now actually works. It was appearing whenever the phone had a share button at all, then failing every time, because Chrome refuses to share .json files. It now checks what your phone will really accept before offering, and sends a format that works.',
      'An honest correction on my own reporting: I flagged that multiple-choice answers could be guessed by picking the longest option, at 40% versus 25% by chance. That measurement counted "longest by three characters", which nobody can see. Measured properly — longest by a margin you can actually spot — the shortcut scores exactly chance. There was a small real bias in a handful of questions and those were rewritten, and the release check now measures it the right way.',
      'Also verified this round: 25 simulated learners across every course, session length, ability and drop-off pattern (no crashes, no broken promises), 20,000-attempt histories staying fast, and deliberately malformed data being rejected rather than crashing anything.',
    ],
  },
  {
    version: '7.0',
    date: '2026-08-09',
    title: 'Five Things That Make You Think Harder',
    points: [
      'Constraint puzzles: "using these digits, each at most once, fill the boxes to make the largest sum / closest result / biggest product". The arithmetic is easy; the SEARCH is not — you have to work out which slot carries the most weight. Every answer is a true optimum found by exhaustive search, and the release check re-solves each one from the digits printed in the question, so a wrong "best" cannot ship. Same rule the chess tactics follow.',
      'Get ready for the next course: a card in Practice that offers only the prerequisites you do not own yet for the course after yours, foundations first. It counts real independence — having seen something in class does not count — and if nothing stands in your way it says so instead of inventing busywork.',
      'The coach now names your recurring mistakes. Not "you got 12 wrong" but "Misread the problem is a pattern, not a one-off — 9 of your last 12 tagged mistakes, mostly in Percent problems", with the repair that actually fits that cause. Misreads, wrong-method picks, and slips each need a different fix, and none of them is "practise more". It refuses to name a habit from fewer than 8 tagged errors, because two slips is not a habit.',
      '"Prove me wrong" questions: a claim that sounds right, and you find the single case that kills it — squaring always makes a number bigger (try 1/2), the sum of two primes is always even (try 2 + 3). Then a harder version: repair the broken claim so it is actually true. One counterexample ends a "for all" argument, and a thousand supporting examples never establish one.',
      'Send to another device: hands your export straight to Nearby Share, AirDrop, or whatever you pick, with no server involved. A QR-code version was considered and rejected on measurement — a year of practice is about 1.75 MB, which is 607 QR codes.',
      'Bug fixed, found by your own question: your learning goals were being applied one at a time, and each one quietly ate into the ones before it — so picking two goals that pointed different ways cancelled almost to nothing. They now apply together in a single pass. Measured: "Move up in my math course" went from +8 to the full +10 it was supposed to get. The note also stops claiming a big tilt when you pick many goals, because the budget is shared, not multiplied.',
    ],
  },
  {
    version: '6.3',
    date: '2026-08-08',
    title: 'Your Goals, Editable — and Reports You Can Delete',
    points: [
      'Learning focus now lives in Settings: the goals you picked during setup are editable anytime, and four new ones joined the list — "Move up in my math course", "Walk the four Paths", "Learn how to learn", and "Stronger science & physics". Same honest rules as always: together your goals tilt the long-run balance by a bounded ~12 points, everything unpicked keeps its floor, and a goal cannot exist in the picker without a real effect wired to it.',
      'Problem reports can now be deleted: Settings → Data → "Delete problem reports", behind a confirm, with export offered first. Reports are your notes about broken questions, not learning evidence — deleting them touches nothing else.',
      'The storage breakdown now says what the "learning data" figure includes (its automatic backup copy and database overhead) and that the true history is what Export produces — usually far smaller.',
    ],
  },
  {
    version: '6.2',
    date: '2026-08-08',
    title: 'The Storage Number, Explained by Itself',
    points: [
      'Settings → Privacy & storage now breaks the usage number down (on browsers that expose it, like Chrome on Android): how much is the cached app itself, how much is your actual learning data, and that the rest is browser bookkeeping. Prompted by a real question — a barely-used profile showing 75 MB. The answer: almost all of that is the app files kept for offline use plus the browser\'s own overhead; the learning history itself is kilobytes, and grows a few MB per year of daily practice.',
    ],
  },
  {
    version: '6.1',
    date: '2026-08-08',
    title: 'For Everyone Middle School Onward — Courses Up Through College',
    points: [
      'Three more courses join the ladder: Geometry (HS), Algebra 2 / Precalc, and College & beyond — a quantitative-fluency refresh for students past high school and adults returning to math. The question is now "what math course are you in right now?", with an honest "None right now" for everyone else, because this app is for anybody middle school onward, in school or not. Grade level gained 12th and a "Not in school" option to match.',
      'Choosing a course never boxes you in: harder and easier material still flows exactly as before. The course is a small open tilt on top of the same difficulty dial, reviews, and rotation — a 7+ student who is cruising still meets harder problems, and one who is struggling still gets easier ones. That was already true; the copy now says it out loud.',
      'The app now checks in about your course every few months — one quiet card on Today, because semesters end and classes change, and a stale course selection would quietly mis-tilt the plan. Confirming is one tap; there is no red dot, no nag, and it waits as long as you like.',
      'New high-school problem families where the shelf was thin: choosing and using trig ratios, composing transformations, similar-figure solving, circle sectors and arcs, sliding function graphs (the backwards inside-shift, tested properly), and logarithm structure — logs turning products into sums.',
      'A research sweep of the wider landscape — Brilliant, Alcumus, Beast Academy, IXL, DeltaMath, Desmos, OpenStax, Paul\'s Online Math Notes, MIT OpenCourseWare, Math Academy and more — is now in the ledger as a ranked mining list for future content, with licensing notes so inspiration never becomes copying. The standing rule holds: problem KINDS are borrowed, every problem here is original, every answer computed.',
    ],
  },
  {
    version: '6.0',
    date: '2026-08-08',
    title: 'The App Now Knows What Class You Are In',
    points: [
      'You can tell the app your actual math course: Math 6 (review), Math 7, Math 7+ (accelerated), or 7/8 Algebra — set during onboarding or anytime in Settings. The course maps were built from the real thing: the verbatim Common Core standards California adopted, the state\'s own definition of the accelerated 7+ pathway (all of 7th plus the first half of 8th), district course descriptions, and the placement tests districts actually use for algebra readiness. Sources are in the research ledger.',
      'What choosing a course does — and deliberately does not do: course skills get a small, openly-labeled priority bump, the same bounded-tilt law your goals follow. Every selection says so in its "why". Nothing outside the course is dropped, the practice-balance sliders still rule, and a due review still outranks course membership. Skills that UNLOCK your course\'s material get a smaller bump too — added after a simulation showed a fresh learner on the algebra track spending a year staring at locked doors.',
      'The coach now reports course progress honestly: how many course skills are independent-or-better (never "we covered it in class" — guided exposure does not count), and which unit is next. When you finish a course, it names the next one and changes nothing until you choose it.',
      'About 70 new problem families, built from what those courses actually assign: systems by elimination with the classic mixture/chase/age word problems, every form of a linear equation, two-variable inequalities and their systems, function domain/rate-of-change/inverses, sequences in recursive and explicit form, exponential models from percents and tables, compound probability, sampling and scale drawings, GCF/LCM, and a proper set of AoPS-style non-routine problems (working backwards, invented operations, extremes, digit algebra). Wrong answers are not random: they encode the documented mistakes real students make.',
      'The ceiling moved up too: quadratics by vertex form and formula, radical arithmetic, rational exponents, finite and infinite series, permutations and combinations, and logarithms as "the exponent finder". And every other part of the app grew — two new hard families each for Observer, Investigator, Strategist, Insight, Meta, science, physics, and coding.',
      'Three new readiness probes (a waiting-line law, voting cycles, and estimating a total from the biggest serial number seen) bring the pool to nine — about a school quarter of weekly runway. One collision caught by the release gate mid-build: a new counting family teaches the handshake formula an existing probe relied on, so the probe was rebuilt on the part of its idea that stays untaught. The gate exists for exactly this.',
      'Two honest corrections along the way: variability-and-distributions was labeled an 8th-grade skill when IQR and MAD are verbatim 6th-grade standards (fixed after actually reading them), and one requested source — a "Tapis" Algebra 1 textbook — could not be identified as a real book, so it was flagged rather than silently invented.',
    ],
  },
  {
    version: '5.2',
    date: '2026-08-07',
    title: 'The Readout I Shipped Yesterday Could Never Actually Appear',
    points: [
      'Last release added "how fast you pick up something new" — and shipped three of them against a readout that needs four before it will say anything. The only way to reach four was to do one twice, and the second time you are remembering an idea rather than picking it up. The number was unreachable by any honest route. I have not fixed that by lowering the bar to three, which would have been the dishonest repair.',
      'There are now six: clock arithmetic, Simpson\'s paradox, the pigeonhole principle, why extreme results drift back, counting links two ways, and the first-digit rule. Repeats no longer count at all — only your first meeting with each idea, so nothing can be padded by re-reading.',
      'One of the original three has been retired. It taught how an algorithm\'s work grows, which this app already teaches in the coding path — so for anyone who had done that, it was measuring memory, not pick-up. I found it by searching the whole question bank for the idea rather than by reading my own code, and that search is now a release check: every probe has to name the idea it teaches, and the app refuses to build if ordinary questions teach the same thing.',
      'Probes now show up in your normal session too — at most once a week, always the very last thing, and never in a session under 15 minutes. They advance nothing, so they should never push practice or reviews aside, and putting them last means stopping early costs you only the part that does not count. Over a simulated year that works out to all six in about six weeks, half of them landing on ideas whose groundwork you already had and half not, which is what makes the comparison mean anything.',
      'A content bug caught by checking rather than trusting: the new network questions were showing lists of connections that could not physically exist — four of the twelve versions — and then teaching you how to spot exactly that kind of impossible list. Every version is now checked mathematically before it can ship.',
      'Being straight about a limit: each idea is only new once, so after about six weeks you will have met all of them and the number stops moving. It tells you how well new ideas land, not whether that is improving. Measuring the improvement would need a constant supply of genuinely new ideas, and I would rather say that plainly than let a frozen number look like a trend.',
    ],
  },
  {
    version: '5.1',
    date: '2026-08-07',
    title: 'A Second Way of Measuring — How Fast You Pick Up Something New',
    points: [
      'Last release admitted the biggest gap in how this app measures you: it only ever tests you cold, with no resources, which understates what your practice actually bought. The alternative from that literature is to measure how well you learn something new — so there is now a "Learn something new" card in Practice that teaches a genuinely new idea for about a minute, hides the explanation, and asks questions you can only answer from it. Clock arithmetic, Simpson\'s paradox, and how an algorithm\'s work grows are the first three.',
      'These do not advance anything, and they are not meant to. A probe hands you the explanation, so getting it right proves nothing about what you own — it is recorded as exposure, the same as reading something. It cannot promote a skill, schedule a review, or count as a first-try win. A wrong answer is not held against you either, because failing to pick up an idea you met ninety seconds ago is not a gap in your knowledge.',
      'The readout compares you to yourself: how often ideas land when you already had the groundwork versus when you did not, judged by what you knew at the time of each probe rather than what you know today. It refuses to say anything under four probes, and stays silent on the comparison until both sides have samples. There is no norm and no cohort — three probes is enough to make a readout appear, not enough to characterise anyone, and it says so.',
      'A bug worth naming, found by playing one: the screen congratulated a correct probe with "unaided, first try — that is the evidence that advances skills", on the one activity where the explanation had just been handed over. The scoring underneath was right; the sentence was not. Worse, six other places counted a correct answer as unaided without re-checking whether help was given — enough perfect probes would have talked the coach into calling a subject "a strength" while you were at 50% on real work. Fixed at the source, so all of them drop probes at once.',
      'Difficulty stars no longer borrow the words the mastery ladder uses. Levels 2 and 3 were called "Guided" and "Independent" — the same two words that mean specific things about what you have proven — so a 3-star question answered with three hints displayed the word "Independent" on screen. They are now "Routine" and "Combining", and a test keeps the two scales from sharing vocabulary again.',
    ],
  },
  {
    version: '5.0',
    date: '2026-08-07',
    title: 'Transferred Was Being Awarded Too Easily — Including for Being Told the Answer',
    points: [
      'Four questions were handing out the app\'s highest rung for something that is not transfer. The "same thing elsewhere" items open by naming the pattern — "The pattern: a fact was observed, and a motive was invented" — and then ask you to find an instance of it. Being told which idea applies and then applying it is application, not transfer; the standard test in this literature is that transfer has to happen without the prompt. Those four still exist, because cued practice is genuinely useful, but they no longer count as transfer evidence, and their explanation now says so instead of claiming that "nothing in real life arrives tagged with which idea applies" while the prompt did the tagging.',
      'Transferred now needs distance on two counts, not one. It used to fire on an unfamiliar question form alone — same subject, same answer format, same sitting, only the surface changed. The standard taxonomy in this field puts transfer distance on nine separate dimensions, and moving one of them is near transfer. It now takes an unfamiliar form PLUS a different subject, a different answer format, or a real delay, and your Progress screen names which ones you actually crossed.',
      'Expect this rung to be rare. Simulated across a year of daily practice, 2 skills out of 47 reach it. That is not a bug to be tuned away — far transfer is the hardest and least reliable result in this whole literature, and a top rung that everybody reaches is measuring something else.',
      'Being straight about the ceiling: of those nine dimensions the app can only observe four, because it runs on one device and sees only your answers. It cannot know where you were, what you were trying to get done, or who was with you — so it never claims those. One of the four, "different subject", turns out to almost never fire in practice, because every activity belongs to exactly one subject by design. That is written into the research ledger rather than left to look like it works.',
      'What was not built, and why: the strongest criticism of how this app measures anything is that testing you cold, with no resources, underestimates what your practice actually bought you — the alternative being to measure how much faster you learn something new. That needs a whole new activity type and a second kind of evidence that is deliberately not a rung, and done carelessly it becomes exactly the soft self-reported progress number this app refuses. It is recorded as the biggest known gap rather than half-built.',
    ],
  },
  {
    version: '4.3',
    date: '2026-08-07',
    title: 'Ten-Minute Sessions Were a Different App',
    points: [
      'A short session — ten minutes or under — was skipping the thinking-lab block entirely. Simulated across a full year at ten minutes a day, that meant 73% of practice went to mathematics, only 19 skills were ever touched against 42 to 58 for every other pattern, and the four Paths were never scheduled once. If you practised in short bursts you were quietly using a narrower app.',
      'Short sessions now include one lab item, paid for out of the core block so the session stays the length you asked for. It alternates on its own, because a lab day clears that area\'s shortfall and the next day goes back to academic work. After the fix the same ten-minute learner reaches 43 skills instead of 19, with mathematics at a normal 36%.',
      'The balance adjustments moved. They used to sit above the chart in warning orange, so a routine note about your goals read like something had gone wrong; they now sit inside the card under "Adjusted this week", in the quiet palette, with every adjustment listed instead of only the first.',
      'This came out of running a simulated year across ten different learners — daily and three-times-a-week, ten to forty-five minutes, strong, average, struggling, plateaued, low-energy, and several goal combinations. Nine of the ten were healthy: difficulty climbing from about 2.1 to between 2.7 and 3.2, accuracy settling at 80–93%, review backlogs staying manageable. The ten-minute learner was the one that was broken.',
    ],
  },
  {
    version: '4.2',
    date: '2026-08-07',
    title: 'Your Goals Now Do Something',
    points: [
      'The goals you picked during setup were being saved and then read by absolutely nothing. Choosing "Improve at chess" or "Be ready for high-school math" changed not one thing about what you were given — which is worse than never asking, because asking implies a promise.',
      'They now tilt your long-run balance toward the areas they lean on, by about twelve percentage points in total. Picking six goals spreads that same twelve points wider rather than tilting six times as hard, because choosing everything should mean broad emphasis, not extreme emphasis.',
      'Nothing you did not pick gets dropped. Every area keeps its floor and stays in rotation, so you still learn it — just less often. The Coach lists the tilt among its adjustments, so you can see it and turn it off with coach-managed balance.',
      'On whether practice is spread too thin to learn anything: I simulated 120 days of 30-minute sessions to check. It is not. Every area cycles through its skills in roughly one to one-and-a-half weeks, 53 of 97 skills get real practice in four months, and each area gets three to five skills to Independent or beyond. Time per area tracks its target within a couple of points.',
    ],
  },
  {
    version: '4.1',
    date: '2026-08-07',
    title: 'The Work Actually Gets Harder Now',
    points: [
      'The biggest fix here came from a question worth asking: do the problems really get harder as you improve? Simulating a learner for 120 days said no. Someone answering 95% of questions correctly was still being handed difficulty 2.4 in week 17 — the same as in week 3. Four months of practice, no change in challenge.',
      'Two causes, both structural. Once a skill reached Retained it left the pool completely, so you were permanently working at the frontier of NEW material — and new material starts easy by definition. And reviews were capped at difficulty 3 no matter how well you were doing. So difficulty could not rise even in principle.',
      'The app now watches your recent unaided accuracy and moves the dial. Above about 82% first-try it raises difficulty; below 50% it lowers it; in between it holds, because that band is where work is hard enough to be worth doing and still winnable. Skills you own come back for harder work instead of being retired, and the review ceiling lifts when you are clearly cruising.',
      'Choosing between two available questions is no longer symmetric either. One rung too hard and one rung too easy used to count as equally bad matches; too-easy is now penalised more, because a comfortable session is pleasant and teaches little.',
      'After the change, the same simulation ramps from difficulty 2.10 in week 1 to 2.87 by week 5, and first-try accuracy settles at 75–92% instead of drifting up to 98%. A simulated struggling learner gets the opposite treatment — difficulty eased when accuracy fell to 47%, and their accuracy recovered.',
      'The Coach now says so out loud. "Model of Me" states what the difficulty dial is doing, the accuracy it is reading, how many attempts that rests on, and what it does not know — including that the thresholds are a rule of thumb rather than a measured optimum. A coach that changes your work silently is worse than one that never changes it.',
      'Scientific reasoning gets its advanced tier, the last bucket that was thin: confounds that survive the controls a study lists, what a bigger sample actually buys you (precision follows the square root, so 16× the people buys 4× the precision), reading a headline against the study underneath it, and designing the test whose results would actually point in different directions. Several items deliberately score "reject it" as WRONG — scepticism that dismisses everything is its own failure, and it feels sophisticated, which is what makes it dangerous.',
    ],
  },
  {
    version: '4.0',
    date: '2026-08-07',
    title: 'An Advanced Tier, Placed Where the Bank Ran Out',
    points: [
      'Twelve new question families at the top two difficulty levels, aimed by measurement rather than by feel. Counting first: 57 of 97 skills had nothing above difficulty 3, and Meta Lab had no hard question at all — so however well you did, the planner had nothing harder to reach for. That is a content ceiling, and only content fixes it.',
      'Math: sign discipline (a negative distributed across a difference, then evaluated at a negative), equations with no solution or infinitely many, successive percent change and why the round trip never returns, working backwards from a midpoint, exponent laws colliding with a zero power, shaded-region area, and ratios that change when a fixed count is added to one side.',
      'Meta Lab went from zero hard questions to three families: judging what study evidence actually supports, reading your own confidence against your accuracy, and telling an explanation apart from an instruction. These ask you to evaluate claims about learning rather than recite advice about it.',
      'Observer gains pulling a report into its separate claims and finding the weakest; Guardian gains pressure that arrives under a friendly surface — a manufactured cost attached to your refusal, a checkable claim about what everyone else did, a line that makes thinking itself look like not caring.',
      'Every numeric answer is derived from the question\'s own generated values and was re-checked by parsing the finished question back out and recomputing it independently — so an answer cannot quietly drift from the problem it belongs to. Guessing by answer shape is unchanged at 28.5% against a 25.4% baseline.',
      'Physics and coding got the same treatment in the same release. Physics: average speed over two legs (which is not the average of the two speeds), reading distance as the AREA under a velocity–time graph rather than the slope, collisions where the two objects lock together, equal-and-opposite forces producing unequal accelerations, what a second bulb does in parallel versus in series, and the density of an object made of two materials.',
      'Coding: two names pointing at one list, boolean operators that stop early so the right-hand side never runs, a break that exits only the inner loop, what a function can and cannot change about the values you pass it, and choosing between two correct algorithms when one is faster per step but does vastly more of them.',
      'Every code question was verified by pulling the code back out of the finished question and running it, then comparing the output to the stated answer — 44 renders, all matching. Physics answers were re-derived from the rendered numbers the same way.',
      'Where that leaves the ceiling: physics went from 3% hard questions to 20%, coding from 9% to 25%, and the number of skills with nothing above difficulty 3 fell from 57 to 37. Scientific reasoning is now the thinnest at 13%, and that is the next one.',
    ],
  },
  {
    version: '3.9',
    date: '2026-08-07',
    title: 'One If-Then Plan, No Log to Read',
    points: [
      'When a Path skill has been held long enough to actually use — Retained, not merely learned — the end of that session asks for one if-then plan: "if someone pushes me to decide right now, then I say I\'ll answer tomorrow." Two short boxes, about twenty seconds.',
      'There is nothing to come back and read. Writing the plan is what does the work; re-reading it adds almost nothing, so no log or journal screen was built. Roughly two weeks later, one session ends by asking whether that situation ever came up — three buttons, then it is done and never asked again.',
      'It is not scored and it moves no rung, ever. Real life cannot be machine-checked, so anything you report about it is self-assessment — which this app refuses as evidence everywhere else, and refuses here too. A test now locks that: a plan reporting "I used it" changes no skill state, schedules no review, and cannot create a rung on its own.',
      'Paths only. Your math is already checked by the app and by school; the four Paths are the ones whose whole point is outside the app.',
      'The plans you write are listed at the bottom of Progress, with what you reported back — newest first, below every evidence section, and labelled as not being evidence. Nothing chases you to read it; it is there if you want it. It also travels in your export like everything else.',
    ],
  },
  {
    version: '3.8',
    date: '2026-08-07',
    title: 'Structure Bridges — Aimed at Using This Outside the App',
    points: [
      'Every Path gains two new question types built specifically to make the ideas usable outside the app. "Shared structure" shows you two situations that look nothing alike — a show you keep buying tickets for, and a company funding a dead project — and asks what is the same underneath. "Same thing elsewhere" gives you the pattern and asks you to find it in an unlabelled third situation.',
      'The wrong answers are deliberately surface matches: both involve money, both happen at school, both are people behaving badly. Matching on surface and missing structure is exactly the failure that stops a skill leaving the app, so it is the thing being trained against.',
      'This shape was not a guess. Comparing two examples is the version of this that works in the research; abstracting a principle from a single example — teach one case, then state the rule — is close to the version that was tested and largely failed. That is roughly what most explanations in this app do, so these items do the other thing.',
      'Being straight about the ceiling: nothing here guarantees you will use this in real life, and no honest app can promise that. What it can do is train recognition on the kind of question where the answer is not labelled, which is what real situations are like. The research ledger records the full claim, its limits, and the piece still missing — if-then plans tied to real situations in your own life.',
    ],
  },
  {
    version: '3.7',
    date: '2026-08-07',
    title: 'Best Explanation — the Investigator Gets the Missing Half',
    points: [
      'New Investigator skill: Best explanation. The Path could already deduce from premises, update a belief with evidence, and test rival hypotheses — but nothing taught you to GENERATE the explanations in the first place, or to choose between two that both fit. That is the actual detective move, and it was missing.',
      'Four question families. "Explain all of it" — the wrong answer covers most of the evidence and quietly drops one observation. "Fewest coincidences" — two stories both fit, so you count what each needs you to accept without evidence; a more detailed story is more expensive, not better supported. "What is it resting on" — name the one fact an inference depends on, because sharp deduction in any subject is specific knowledge, not general cleverness. And "When the evidence will not decide", where the correct answer is repeatedly "leading candidate, not proven — here is the test that would settle it".',
      'The scenarios reason about objects, places and events — never about reading a person\'s character or history from how they look. That famous version of this trick is cold reading, which this app refuses to teach anywhere.',
    ],
  },
  {
    version: '3.6',
    date: '2026-08-07',
    title: 'The Balance Sliders Actually Have to Be Dragged',
    points: [
      'The practice-balance sliders now only respond to a real drag of the handle. Pressing anywhere else on the line does nothing at all.',
      'The previous attempt at this only worked with a mouse. A standard slider jumps to wherever the line is pressed, and the code cancelled that jump on press — but touch never goes through that path, so on a phone the tap-to-jump survived untouched. The sliders are now built from scratch rather than restyled, so the behaviour is the same on touch, mouse and keyboard.',
      'Only the handle claims a touch gesture, so swiping anywhere else on the row still scrolls the page normally. The handle is a 44px target, keeps its own focus ring, and arrow keys, Page keys, Home and End all still adjust it — dragging is required for pointers, not for keyboards.',
    ],
  },
  {
    version: '3.5',
    date: '2026-08-07',
    title: 'Harder, Longer, and Honest About Mastery',
    points: [
      'Mastery got substantially harder to reach, because it should mean you can actually use the thing. "Independent" used to accept two versions of the SAME question generator — the same problem with different numbers, counted as two. It now requires two genuinely different question families, and the four Paths require three, since observation, logic, strategy and influence-defence are the easiest skills to pass by recognising a familiar question shape rather than thinking. Some skills will drop a rung when this recalculates. Nothing was lost; the old rung was not earned under the stricter rule.',
      'A session no longer ends early. Planned minutes are only estimates, so a "30 minute" session could finish in twelve real ones. It now tops itself up with fresh work until it is within five minutes of the length you chose, always stopping at a block boundary rather than mid-problem, and never starting something that would run it long. A minute counter sits in the session header — counting up, not down, because a countdown turns thinking time into time pressure.',
      'Your phone stays awake during a session, placement, or exam. Thinking time is not idle time, and the screen locking mid-problem was interrupting the one thing this app is for.',
      'Fixed: the same problem could appear twice in a row. When the session stepped difficulty up or down it picked the replacement from the same skill — without checking what you had already been given, so it could hand back the question you had just answered. Reported from real use, reproduced, and now covered by a test that fails against the old behaviour.',
      'First sessions after the diagnostic start much closer to your actual level. Every skill previously began at the easiest difficulty regardless of what placement had just watched you do, and the planner kept parking on foundational material because "other skills depend on it" — even when placement had already cleared it. Measured across a full plan, mean difficulty rose from 2.0 to 2.5 with no bottom-rung items at all.',
      'No block can be filled with clones of one question family any more. A skill with only one question type was quietly repeating it up to seven times in a single block; the cap is now two, and the session fills the rest from elsewhere.',
    ],
  },
  {
    version: '3.4',
    date: '2026-08-06',
    title: 'First Day of Real Use',
    points: [
      'The practice-balance sliders now have to be grabbed. Tapping anywhere on the track used to jump the value to that spot, and a swipe that merely started on a slider was read as a drag — so passing through Settings could quietly rewrite your targets, and since moving one slider rebalances the rest, a bump you never noticed changed several areas at once. Only the handle responds now; tapping elsewhere on the track selects the slider so the arrow keys can nudge it, without changing anything.',
      'A "Reset to recommended" link sits under those sliders, appearing only once something has actually moved. There was previously no way back from an accidental change.',
      'Quiet hours for review reminders now read on the 12-hour clock — 9 PM to 7 AM instead of 21:00 to 7:00 — with midnight and noon written out, since "12 AM" is read backwards about half the time.',
      '"Export problem reports" in Settings → Data used to appear only after you had filed a report, which made it impossible to find when you went looking for it. It is always listed now, and when empty it explains where reports come from: the flag icon at the top of any question.',
      'Four layout breaks fixed, found by sweeping every screen for content escaping its container at both 375px and 320px, with relaxed text spacing on and off. The quiet-hours pickers pushed the second dropdown clean out of its card; the balance sliders shoved their own percentage readout past the card edge; the Progress tiles let single words like "Independent" spill out; and the Coach tone selector pushed the entire page sideways. Only the first needed relaxed spacing to show up — the rest were already broken on a narrow phone and spacing just made them obvious.',
    ],
  },
  {
    version: '3.3',
    date: '2026-08-06',
    title: 'Updates Install Themselves Before You Start',
    points: [
      'On the very first screen — the one asking for a nickname and age band — a waiting update now installs itself instead of waiting to be tapped. The refresh banner lives inside the main app shell, which that screen does not render, so an update arriving during setup previously had no way to be applied at all.',
      'After setup nothing changes: you still get the banner and decide when to reload, and it still never appears during a session, placement, or exam.',
    ],
  },
  {
    version: '3.2',
    date: '2026-08-06',
    title: 'The Bridge to High School, and an Honest Count',
    points: [
      'Four topics the app talked around without ever teaching are now covered: absolute value, arithmetic and geometric sequences, right-triangle trigonometry, and reading a trend line off a scatter plot. These are the first things the high-school sequence assumes you already have.',
      'Game theory gained the two ideas a course opens with rather than ends with: that you should play the game before analysing it, and that changing what the outcomes are worth changes what a rational player does. Both are checkable questions, not lectures.',
      'Unit checkpoints arrive on Today once you own enough of a unit and enough of it has gone cold — a short cumulative pass across the whole unit instead of one skill at a time. It appears when the evidence says it is due and stays away otherwise.',
      'Fermi estimation was a single question wearing a variant count. It now has eight estimates and a second family that asks you to audit somebody else\'s estimate — find the factor with the widest range, convert a total into a rate you have intuition about, and resist averaging two answers that disagree by 60×.',
      'The variant audit had a hole: it treated a reshuffled option list as a brand-new question, so a template with three real questions could claim thirty-six. Forty-four templates were overstating themselves. Every count now matches what the generator actually produces, and the honest total for the whole app is about 216 hours of distinct material rather than 231.',
      'Nothing was deleted to achieve that. Where a question bank existed but random selection kept missing it, the app now cycles through every case before repeating any — several families gained real questions that were always there and rarely shown. The right-triangle template went from three real questions to thirty-six.',
      'A new release check refuses to ship a skill whose evidence ladder cannot be climbed — too few question forms to ever reach Independent, or a single question family so Transferred is unreachable by construction. It found one on its first run.',
    ],
  },
  {
    version: '3.1',
    date: '2026-08-06',
    title: 'You Can No Longer Guess by Reading the Options',
    points: [
      'Multiple choice used to leak the answer through its shape. Correct options were the careful, fully-qualified ones and the wrong ones were short dismissals you could rule out on sight, so "always pick the longest" scored 52.8% against a 25% baseline — half the questions were clearable with no knowledge at all. Roughly a hundred distractors have been rewritten as equally specific, equally tempting statements. That strategy now scores 30.7%, and the build fails if it ever gets back above 34%.',
      'The side effect is that the questions genuinely got harder. A wrong answer that is a full, reasonable-sounding position takes actual understanding to reject, rather than a glance at how short it is.',
      'Fixed several sentences that read wrongly because a value was dropped into them: "on-time returns was 58%", "library text reminders improves…", "longer rotor blades always causes…", and a lower-case word opening a sentence. All were plural phrases meeting a singular verb. The audit now fails any sentence that starts in lower case where a value was interpolated, so this class cannot come back.',
    ],
  },
  {
    version: '3.0',
    date: '2026-08-06',
    title: 'Show Your Work — and the App Reads It',
    points: [
      'Some problems now ask for the middle values, not just the answer. Each line is checked on its own, so when the final number is wrong the app tells you exactly which step broke — and everything after it follows from that one line, so it is the only one worth redoing.',
      'That kills the last piece of self-assessment in the app. You used to be asked to classify your own mistake afterwards, which is guesswork dressed as data. Now the broken step names it: a wrong base in a percent problem is a concept gap, right base with wrong multiplication is a slip, and those need completely different repairs. The tag comes from your work, not your opinion of it.',
      '"Transferred" now means something measured. It used to fire whenever an item an author had tagged as a transfer item was solved — so a label decided the top rung. It now also requires the problem to come from a question family you have never practiced that skill on, checked against your own history. Some skills may drop back from Transferred to Retained, because that rung had not actually been earned.',
      'The daily session interleaves once a skill is yours. Below independence it stays blocked on one skill, which is right for learning something new. Above it, the core block mixes in neighbouring skills — because on a real test the hard part is recognising which method applies, and blocked practice never trains that.',
      'Sessions now adapt as they go. Two misses in a row and the next problem steps back a level; three clean and it steps up. It says so when it happens rather than adjusting behind your back, and it never changes what an attempt is worth.',
      'Confidence ratings finally do something. When your stated confidence is running well ahead of or behind your accuracy, the session favours items that ask you to rate it, and the coach says why.',
      'The app got faster where it was quietly getting slower. Every submitted item used to replay your entire history about five times over; that is now cached. The Today screen was recomputing its four most expensive figures on every single render because of a stray timestamp.',
    ],
  },
  {
    version: '2.2',
    date: '2026-08-06',
    title: 'More Questions, and Harder Ones That Are Honest',
    points: [
      'A big content release: about 46% more distinct material than before, and for the first time every declared variant count has been verified to equal the number of genuinely different questions the generator produces. No category now recycles its material inside a year.',
      'Algebra gained a full strand — 22 new question families from easy on-ramps up to non-routine work. Several are deliberate traps: the inequality where dividing by a negative flips the sign, the equation with no solution or infinitely many, squaring a sum, a sum of squares that looks factorable and is not, zero slope versus undefined slope. Their wrong answers are the tempting-but-wrong ones, so a miss names the misconception instead of just scoring zero.',
      'Game theory became a real subject rather than two payoff tables: best response, dominance, finding the stable point, the dilemma where the stable outcome is worse for everyone, coordination versus conflict, repeated play, credible commitment, spotting a threat nobody would carry out, and thinking one step further than the other side. Two new skills track it, and every answer is computed by actually analysing the generated game.',
      'Physics gained five more question families with exact, typeable answers — average speed over two legs (which is not the average of the speeds), net force, height-to-speed energy conversion, density, and Ohm\'s law rearranged.',
      'A generator stress sweep found real defects that had shipped. Two items were literally unanswerable: one demanded 55.00000000000001 and another 13.333…, values no keyboard produces. A studio was printing "0.3999999999999999 higher than control" into its prompt, its options, and its model report. A boolean-logic question offered only two options, making it a coin flip. All fixed, and each defect class is now a release-blocking audit rule.',
      'Multiple choice can no longer be beaten by test-wiseness. Correct answers were the careful, fully-spelled-out ones and distractors were short dismissals, so "always pick the longest option" scored 52.8% against a 25% guessing baseline — you could clear half the questions knowing nothing. Distractors have been rebuilt to be equally specific and equally plausible, and the build now fails if that strategy ever gets back above 45%.',
    ],
  },
  {
    version: '2.1',
    date: '2026-08-06',
    title: 'Every Error Gets a Repair',
    points: [
      'The corrective loop now covers all of your work. Case files, work studios, and the "which method?" drill used to show the explanation after a wrong checkpoint and move straight on — no corrected attempt. That was about 30% of every graded thing in the app, including all 360 forms of the method drill, which is the activity that trains recognising what kind of problem you are looking at.',
      'A wrong checkpoint now stops and offers the same fork the single problems always had: try again, or have it walked through. Getting it right after a correction counts as guided evidence — it can never become independent evidence, and a hint anywhere in the activity still disqualifies the whole thing.',
      'Repairing an error is no longer treated the same as walking away from one. Previously a multi-part activity was scored purely on first attempts, so correcting your mistake changed nothing. Now a corrected activity earns guided credit, while an abandoned error still counts as a miss and still shortens the review interval.',
      'The method drill scaffolds each of its six checkpoints separately. They are six different problems, so the single shared hint list could not help with any of them; each now has its own ladder that goes from "read the question sentence, not the story" to naming the method.',
      'The coach stops describing your bottleneck and hands you the work. The highest-leverage blocked skill now has a button that starts a focused session on it directly.',
    ],
  },
  {
    version: '2.0',
    date: '2026-08-06',
    title: 'Nothing Grades Itself Any More',
    points: [
      'Self-scoring is gone. Written work used to be rated against criteria by you, and a rating of 75% or better counted as a first-attempt success — meaning a skill could reach Independent on writing nobody checked. It cannot now: only deterministic grading produces evidence, and the mastery replay ignores scores entirely.',
      'Every written artifact became a draft: you write it from memory, then read it beside the model and the criteria. There is no rating control, because neither the app nor you should be grading it. All nineteen of these checkpoints are now followed by an objective probe on the same material — a peer-review discrimination, a repair test, a real problem — and that probe is what counts.',
      'Explain-it-back is the clearest case. You still explain a retained skill from memory, ungraded; then you solve a real problem drawn from that skill\'s own audited bank. An explanation that reads well but cannot drive a problem is exactly the hollow retention this drill exists to catch.',
      'The content audit now enforces all of it: no item can be graded by anything but the validator, no draft may end an activity, and every draft must be followed by a graded part. Three new mastery tests prove that ungraded work never promotes, never counts as a miss, and never moves a review date.',
      'Your history recomputes honestly, as it always has. Past self-scored attempts stay in the log as practice, but they no longer prop up any rung — so a skill that reached Independent purely on self-rated writing will show its real state.',
      'Puzzles are now generated rather than finite. The hand-authored bank held 53 distinct forms against roughly 660 focused minutes a year — the same puzzles three times over. New generators build spatial layouts by partitioning a solved rectangle, and logic grids solution-first with clues pruned against the real solver until exactly one solution survives. Every generated form is verified solvable and unique across its whole variant range.',
      'Observation and deduction gained parameterized families with computed answers: scene audits, delayed-recall stock checks, natural-frequency base-rate problems, and validity checks. No category now recycles its material inside a year — the worst was three times over, and the audit fails the build if any declared variant count is padded.',
    ],
  },
  {
    version: '1.9',
    date: '2026-08-06',
    title: 'Authentic Work, Not Worksheet Theater',
    points: [
      'Authentic Work upgrades the existing Case File mode into a studio for projects, evidence writing, program building, experiments, original-book seminars, expert office hours, field investigations, real-life decisions, and difficult Guardian conversations.',
      'Nine long-form studios provide 70 generated scenarios and more than 400 staged checkpoints. Each preserves a real workflow—brief, evidence, objective decisions, substantial artifact, critique, and revision—while stating exactly what the offline simulation cannot reproduce.',
      'Nineteen new real-world question families add 284 automatically graded variants across receipts, unit prices, travel time, energy use, automations, bug reports, household experiments, source claims, schedules, subscriptions, privacy, boundaries, incident response, project triage, and constraint-safe packing.',
      'Serious drafts now require meaningful word counts, provide deliverable-specific prompts, and compare against explicit models and criteria. Self-assessed artifacts remain separated from verified mastery evidence.',
      'Long multi-stage work now resumes at the exact checkpoint after a reload—including the unfinished draft and rubric state. Every new activity belongs to one of the ten existing percentage categories; the coach can periodically schedule a whole studio from an under-target category when time, readiness, energy, and active missions permit, but never squeezes one into a short block.',
    ],
  },
  {
    version: '1.8',
    date: '2026-08-06',
    title: 'A Real Difficulty Ladder',
    points: [
      'Practice balance now uses real percentages that always total 100%, with a hard 5% minimum for every category. Learner slider changes and temporary coach boosts rebalance the remaining flexible share without breaking any floor.',
      'The four thinking Paths gain 12 new question families and 100 more deterministic variants. Every Path now has automatically graded practice at all five difficulty levels, from direct foundations through multi-constraint expert synthesis.',
      'The five-star system is defined everywhere it appears: Foundation, Guided, Independent, Advanced, and Expert. Stars measure reasoning complexity, not learner worth or speed, and active questions display both stars and the level name.',
      'Difficulty filters use readable numbered stars, activity cards expose level names, and the complete guide explains what changes from one level to the next.',
    ],
  },
  {
    version: '1.7',
    date: '2026-08-06',
    title: 'Four Paths, Fully Checkable',
    points: [
      'Each of the Observer, Investigator, Strategist, and Guardian Paths gains four new deterministic question families: 126 additional variants spanning exact recall, evidence boundaries, logic, Bayes, separating tests, payoff tables, dependency planning, expected value, estimation, ethical strategy, pressure defense, boundaries, and de-escalation.',
      'Every new Path question is automatically graded from an authored or computed answer key. A release-blocking test proves every correct response passes and a deliberately wrong response fails across all 126 variants.',
      'Practice emphasis initially introduced a protected breadth floor; version 1.8 replaces its relative weights with a clearer true-percentage model.',
      'Mobile sheets regain full bottom padding on every phone, including devices without a notch, and bottom navigation gets edge spacing so actions and focus rings no longer sit outside their boxes.',
    ],
  },
  {
    version: '1.6',
    date: '2026-08-06',
    title: 'Mission Control & Quality Pass',
    points: [
      'Learning Missions turn a test or real-world goal into an exact skill target: choose the date, curriculum skills, and daily focused dose. The planner prioritizes both the targets and any unmet prerequisites, and says so in every session plan.',
      'Today now shows mission readiness from real evidence: targets independent, retained, needing repair, and the next prerequisite or skill the session will pursue.',
      'The default program is 30 focused minutes every day. Progress reports the 28-day dose separately from actual outcome evidence, and refuses to call time-on-task learning unless skills cross independent, retained, or transferred thresholds.',
      'Curriculum expansion: variability and distributions, exponential growth and decay, waves and sound, algorithmic complexity, and rigorous experimental design — ten new generated activities with transfer prompts and misconception feedback.',
      'Existing daily sessions now fill the time you selected with fresh generated forms instead of stopping after a fixed handful of activities; a 30-minute plan is tested to schedule roughly 24–33 minutes of focused work without duplicate forms.',
      'Error Clinic now repairs up to three open errors in priority order, distinguishes confidence traps, revisits the failed problem family, then requires fresh reproof instead of drilling only the first error.',
      'Progress adds spaced-review and transfer success rates plus a like-for-like trend that compares only activity families seen in both halves of the month, reducing curriculum-mix distortion.',
      'Interface quality pass: consistent 44px controls, accurate screen-reader progress, safer dialogs and back navigation, equal-height practice cards, clearer time labels, live system-theme changes, and a polished responsive navigation dock.',
      'Reliability and speed: date-only deadlines now use local calendar math everywhere, service-worker update listeners clean up correctly, and screen/curriculum bundles are split into stable cache groups for much faster startup parsing.',
    ],
  },
  {
    version: '1.5',
    date: '2026-08-06',
    title: 'The Proving Grounds',
    points: [
      'Exam Simulator: timed, cumulative, blind mock tests built from your own skill map — no hints, mixed order, answers graded only at the end, then a structured post-mortem that feeds the Error Clinic. Built to close the practice→test-day gap.',
      '“Which method?” drills: real problems from the banks shown as stems — your job is to pick the strategy, not solve. Trains the discrimination step that interleaving research targets.',
      'Explain-it-back: every third session ends by explaining one of your retained skills from memory against its concept card — the self-explanation effect, scheduled.',
      'Personal forgetting curves: once a skill has real review history, its intervals stretch or shrink to fit YOUR lapse pattern (labeled a heuristic, capped both ways).',
      'Named misconceptions: common wrong answers now name the specific trap they represent, not just “incorrect”.',
      'Placement 2.0: a wrong answer on the math ladder triggers an easier constructed follow-up on the same skill, separating slips from real gaps before routing.',
      'Content: five new Case Files (two with values that change every run), three search-and-legality-verified pawn-endgame chess drills, and per-theme chess stats in the skill detail.',
      'Pack Author: build, validate, export, and install your own content packs entirely in-app.',
      'Week in Review: a Sunday ritual card — what advanced, what decayed, minutes by area, your best banked principle, and next week’s objective.',
      'Opt-in review reminders (zero-server: local notifications while the app is open or backgrounded, honoring quiet hours) and read-aloud for item prompts.',
    ],
  },
  {
    version: '1.1',
    date: '2026-08-06',
    title: "The Expansion & the Coach's Ledger",
    points: [
      'Four named Paths — Observer, Investigator, Strategist, Guardian — each with a visible mastery arc, its own code of practice, and per-path progress drawn from real evidence.',
      'Deeper banks everywhere: game theory (dominant strategies, commitment, coordination), algebra and physics depth, and new lab activities across every archetype — plus curated "go deeper" links (optional, online-only).',
      'The Coach shows exactly what it is counting: a live intake of every attempt — daily sessions, Practice launches, reviews, puzzles, case files — all visibly feeding one evidence log, with beliefs that acknowledge puzzle and self-assessed work honestly.',
      'The coach can tune practice balance itself (yours to switch off): bounded, disclosed nudges for deadlines and review pressure, always drifting back to your base.',
      'Quality of life: Enter submits, auto-focused answers, Practice search, batch-safe inputs, focus-trapped dialogs, live-region feedback, ghost-draft and sample-mode isolation fixes, and installed-app update checks on resume and network-regain.',
      'Fixed along the way: Case File self-assessments scoring zero, toggle knobs escaping their track, and a settings gear that finally looks like one.',
    ],
  },
  {
    version: '1.0',
    date: '2026-08-05',
    title: 'The Founding Build',
    points: [
      'A private, offline-first adaptive learning lab: no account, no server, no tracking — everything on your device, exportable and deletable.',
      '84-skill map across math (grades 6–10 into Algebra), physics, coding, scientific reasoning, and six thinking labs; 130+ validated item templates, most parameterized into hundreds of variants.',
      'Evidence-ladder mastery (Unseen → Introduced → Guided → Independent → Retained → Transferred) derived by replaying an append-only attempt log — honest by construction.',
      'A deterministic coach: explainable session plans, spaced review with an adaptive interval ladder, misconception blocks from high-confidence errors, a Model-of-You with stated uncertainty.',
      'The daily session: check-in, retrieval warm-up, academic core with worked-example fading and a repair loop, a rotating lab block, exit ticket, and a deliberate end — crash-proof and resumable mid-item.',
      'Chess tactics verified by exhaustive search, a touch spatial-assembly puzzle, solver-proven logic grids, weekly cross-domain Case Files, a forecast ledger with Brier scoring, and calibration analytics.',
      'Every content item ships with computed answers, hint ladders, worked explanations, and provenance — enforced by an automated content audit in the test suite.',
    ],
  },
]
