/**
 * The verified local knowledge base: one concept card per skill.
 * Cards appear before guided work on an unfamiliar skill and are searchable
 * from the Coach screen. All original text; kept deliberately compact —
 * the app teaches by retrieval, not by reading walls.
 */
export interface KbCard {
  skillId: string
  title: string
  /** Markdown-lite. The idea, the core move, one micro-example. */
  card: string
}

export const KB_CARDS: KbCard[] = [
  // ---- math: number sense
  { skillId: 'm-integers', title: 'Integers, factors & the number line', card: 'Signed numbers mark positions relative to zero; absolute value is distance, so it is never negative. Factors divide evenly, multiples repeat, and GCF/LCM reveal shared structure.\n\nMicro: −6 lies left of −2, so **−6 < −2**, while |−6| = 6.' },
  { skillId: 'm-rationalops', title: 'Rational-number operations', card: 'For signed sums, think position and change; subtracting means adding the opposite. For products and quotients, compute the size first: same signs give positive, different signs give negative. These rules apply to integers, fractions, and decimals.\n\nMicro: −3/4 ÷ 1/2 = −3/4 × 2 = **−3/2**.' },
  { skillId: 'm-fractions', title: 'Fraction arithmetic', card: 'A fraction is a count of equal pieces: 3/4 = three pieces of size one-quarter. **Add/subtract** only with same-size pieces (common denominator). **Multiply** straight across. **Divide** = multiply by the reciprocal ("how many of that piece fit?").\n\nMicro: 1/2 + 1/3 = 3/6 + 2/6 = **5/6**.' },
  { skillId: 'm-decimals', title: 'Decimals & rational forms', card: 'Fractions, decimals, and percents are three costumes for one number. Convert by scaling to a power of ten or dividing. Percent means per hundred: shift the decimal two places.\n\nMicro: 3/8 = 0.375 = **37.5%**.' },
  { skillId: 'm-exponents', title: 'Exponents', card: 'x^n counts multiplied copies, not multiplication by n. Same-base rules follow from counting factors: multiply → **add** exponents, divide → **subtract**, power of a power → **multiply**. Scientific notation: one digit before the point, times a power of ten.\n\nMicro: x³·x⁴ = x⁷ (3 copies then 4 copies = 7 copies).' },
  { skillId: 'm-roots', title: 'Squares & roots', card: '√n asks: which number times itself gives n? Estimate irrationals by bracketing between perfect squares. Squaring destroys sign, so x² = 25 has **two** solutions: ±5.\n\nMicro: √50 is between 7 (49) and 8 (64), just above 7.' },
  // ---- math: proportional
  { skillId: 'm-ratio', title: 'Ratios & rates', card: 'A ratio compares quantities; a **unit rate** rescales the comparison to "per one" — the most comparable form there is. Best-buy, speed, and price problems are all unit-rate problems.\n\nMicro: $7.50 for 5 = **$1.50 per item**.' },
  { skillId: 'm-proportion', title: 'Proportional relationships', card: 'Proportional means y ÷ x never changes (the line passes through zero). Solve proportions by finding the scale factor connecting known parts — cross-multiplication is that reasoning compressed.\n\nMicro: if 3 cm ↔ 45 km, then 1 cm ↔ 15 km, so 5 cm ↔ **75 km**.' },
  { skillId: 'm-percent', title: 'Percent problems', card: 'Percent problems are "of what?" problems — always identify the BASE. Percent change divides by the ORIGINAL. Successive percents multiply (they act on different bases), and reversing a percent divides by what remains.\n\nMicro: after 20% off, price = 80% of original → original = sale ÷ 0.8.' },
  { skillId: 'm-units', title: 'Units & dimensions', card: 'Units are algebra: multiply by fractions equal to 1 (like 1000 m / 1 km) with the unwanted unit positioned to cancel. If the units of your answer are wrong, the answer is wrong — no arithmetic check needed.\n\nMicro: 2.5 h × 60 min/h = **150 min** (hours cancel).' },
  { skillId: 'm-scale', title: 'Scale drawings & maps', card: 'A scale is a ratio between drawing and reality — 1 cm : 4 m means every drawn centimeter stands for 4 real meters. Lengths scale by the factor; **areas scale by its square** (double the sides, quadruple the area). To go from real to drawn, divide; drawn to real, multiply.\n\nMicro: at 1 cm : 4 m, a 22 m wall is drawn 22 ÷ 4 = **5.5 cm**.' },
  // ---- math: data & probability
  { skillId: 'm-stats', title: 'Descriptive statistics', card: 'The **mean** shares the total equally; the **median** is the middle position and shrugs at outliers; the **mode** is the most common. Each answers a different question — pick the summary that matches the question, and know what it hides.\n\nMicro: 1, 2, 3, 94 → mean 25, median **2.5**.' },
  { skillId: 'm-variability', title: 'Variability & distributions', card: 'Center says where data sits; **spread** says how dependable that center is. Quartiles split sorted data into quarters, and IQR = Q3 − Q1 captures the middle half without being dragged by extremes. Compare shape and spread, not only averages.\n\nMicro: equal means can describe a tight cluster or a wild swing.' },
  { skillId: 'm-data', title: 'Data interpretation', card: 'Before reading any chart: check the axes (start point? scale?), the time window, and what is being counted. Then extract exactly the rows/points the question names — no more.\n\nMicro habit: cover the headline, read the numbers, THEN compare.' },
  { skillId: 'm-counting', title: 'Counting principles', card: 'Independent choices **multiply**. Arrangements shrink the choices each slot: n × (n−1) × … Count systematically (organized lists, slot method) — clever beats brute force, but organized beats clever.\n\nMicro: 4 shirts × 3 pants = **12** outfits.' },
  { skillId: 'm-prob', title: 'Probability', card: 'Probability = favorable ÷ total, over equally likely outcomes. Complements: P(not A) = 1 − P(A) — often the shortcut. Independent events multiply.\n\nMicro: P(no six in one roll) = **5/6**.' },
  { skillId: 'm-sampling', title: 'Sampling & inference', card: 'A random sample lets a small group speak for a big one — PROPORTIONALLY. Scale the sample rate up to the population, and expect the estimate to wobble between samples (bigger samples wobble less). A sample only earns this power if it was random; a convenient or self-selected sample answers a different question.\n\nMicro: 12 tagged fish in a sample of 40, lake has ~2000 → about 2000 × 12/40 = **600 tagged**.' },
  { skillId: 'm-ev', title: 'Expected value', card: 'EV = Σ outcome × probability: the long-run average per play. It ranks repeated choices, but a NEEDED threshold can overrule it — maximize the chance of "enough" when only one shot exists.\n\nMicro: (1/6)($12) − (5/6)($1) = $1.17 per roll.' },
  { skillId: 'm-hsdata', title: 'High-school data analysis', card: 'Center and spread describe one-variable data; two-way tables describe categorical relationships; regression summarizes a trend. A residual is observed − predicted, so its sign says which way the model missed.\n\nMicro: observed 18, predicted 15 → residual **+3**.' },
  { skillId: 'm-conditionalprob', title: 'Conditional probability', card: 'P(A | B) means restrict the universe to outcomes where B happened, then ask what fraction also have A. Independence means learning B does not change A: P(A | B) = P(A).\n\nMicro: 12 of 30 club members bike → P(bike | member) = **12/30**.' },
  { skillId: 'm-inference', title: 'Statistical inference', card: 'The design licenses the conclusion. Random sampling supports generalizing to a population; random assignment supports causal comparison. Observational studies can show association, and simulations measure how unusual a result is under a stated model.\n\nMicro: random assignment without random sampling can support causation for participants, not every person.' },
  // ---- math: algebra
  { skillId: 'm-expressions', title: 'Expressions', card: 'An expression is a number-recipe with a placeholder. Only **like terms** merge (3x + 2x = 5x; 3x + 2 stays put). Evaluate by substituting with parentheses — signs ride inside.\n\nMicro: at x = −2, 3x² = 3(−2)² = **12**.' },
  { skillId: 'm-lineq1', title: 'One & two-step equations', card: 'An equation is a balance: whatever you do to one side, do to the other. Undo operations in reverse order (last applied, first undone). Always CHECK by substituting back — it is free error detection.\n\nMicro: 3x + 5 = 20 → 3x = 15 → **x = 5**.' },
  { skillId: 'm-ineqintro', title: 'Intro inequalities', card: 'An equation usually names points; an inequality names a whole region of possible values. Solve simple inequalities by keeping both sides balanced, then show the boundary with an open point (<, >) or closed point (≤, ≥).\n\nMicro: x + 4 ≥ 9 → **x ≥ 5**.' },
  { skillId: 'm-lineqmulti', title: 'Multi-step equations', card: 'Collect x-terms on one side, constants on the other, then divide. Distribute first (or divide both sides by the multiplier when it divides cleanly). Fraction coefficients undo with reciprocals.\n\nMicro: 5x − 4 = 2x + 11 → 3x = 15 → **x = 5**.' },
  { skillId: 'm-inequal', title: 'Inequalities', card: 'Solve like equations with one twist: multiplying or dividing by a **negative flips the direction** (multiply 2 < 3 by −1 and −2 > −3). Sanity-check by testing one number from your answer region.\n\nMicro: −2x < 6 → x > **−3**.' },
  { skillId: 'm-wordeq', title: 'Situations → equations', card: 'Translation is the skill: name the unknown, write each sentence as math, and mark which quantity repeats (gets the x) vs happens once (constant). The equation should re-tell the story.\n\nMicro: "$8 flat + $3/km cost $23" → 8 + 3k = 23.' },
  { skillId: 'm-absolute', title: 'Absolute value', card: '|x| is DISTANCE from zero, so it is never negative. That is why |x| = 7 has **two** answers: 7 and −7 are both seven steps away. An equation with bars splits into two cases; an inequality splits into a band (|x| < 7 means between −7 and 7) or two rays (|x| > 7 means outside them).\n\nMicro: |x − 3| = 5 → x − 3 = 5 or x − 3 = −5 → x = **8 or −2**.' },
  { skillId: 'm-sequences', title: 'Sequences & patterns', card: 'Ask one question first: do you **add** the same amount each step (arithmetic) or **multiply** by it (geometric)? Arithmetic sequences are linear in disguise — the nth term is a + (n−1)d. Geometric ones are exponential in disguise — a·r^(n−1).\n\nThe usual error is counting terms instead of GAPS: reaching the 5th term takes 4 steps, not 5.\n\nMicro: 3, 7, 11, … → d = 4, so the 10th term is 3 + 9(4) = **39**.' },
  { skillId: 'm-trig', title: 'Right-triangle trigonometry', card: 'In a right triangle the angles fix the SHAPE, so the ratios between the sides depend only on the angle — that is the whole idea. Sine = opposite/hypotenuse, cosine = adjacent/hypotenuse, tangent = opposite/adjacent (SOH-CAH-TOA).\n\nLabel from the angle you are using: opposite and adjacent swap when you switch angles. The hypotenuse never moves.\n\nMicro: angle 30°, hypotenuse 10 → opposite = 10·sin30° = **5**.' },
  { skillId: 'm-bestfit', title: 'Scatter plots & trend lines', card: 'A scatter plot shows two measurements per point. Look for **direction** (up, down, none), **strength** (tight or scattered), and **outliers** — in that order, before any line is drawn.\n\nA trend line summarises the pattern, and its slope is a rate with units. Two honest limits: it describes association, not cause, and predicting far outside the data range is guessing with a ruler.\n\nMicro: a trend line through study-hours vs score with slope 4 says about 4 more points per extra hour — in this data, over this range.' },
  { skillId: 'm-coord', title: 'Coordinate plane', card: '(x, y): first across, then up. Signs pick the quadrant. Distances along a grid line are absolute differences of the coordinate that changes.\n\nMicro: (−3, 4) → left 3, up 4 → Quadrant II.' },
  { skillId: 'm-variables', title: 'Dependent & independent variables', card: 'The independent variable is the input chosen or observed first; the dependent variable responds. An equation, table, and graph can all describe the same relationship.\n\nMicro: total cost depends on ticket count, so tickets are x and cost is y.' },
  { skillId: 'm-linear', title: 'Slope', card: 'Slope = rise/run = how much y changes per unit of x — a RATE wearing geometry. From two points: (y₂−y₁)/(x₂−x₁), subtracting in the same order. Flat = 0; downhill = negative.\n\nMicro: (1,2)→(4,11): slope = 9/3 = **3**.' },
  { skillId: 'm-linfunc', title: 'Linear equations & graphs', card: 'y = mx + b: m is the per-unit change, b is the starting value (x = 0). Reading a model: slope answers "per what?", intercept answers "starts where?". They never trade jobs.\n\nMicro: cost = 4·GB + 20 → $4 per GB on a $20 base.' },
  { skillId: 'm-systems', title: 'Systems of equations', card: 'A solution makes BOTH equations true — graphically, where the lines cross. Substitute when one equation hands you a variable; eliminate when coefficients align. Always check in both equations.\n\nMicro: y = x + 1 and x + y = 5 → x + x + 1 = 5 → x = 2, y = 3.' },
  { skillId: 'm-linforms', title: 'Forms of linear equations', card: 'One line, three costumes. **Slope-intercept** y = mx + b shows slope and starting value — best for graphing. **Point-slope** y − y₁ = m(x − x₁) is fastest when you know one point and the slope. **Standard** Ax + By = C makes intercepts easy (set the other variable to 0). Converting between them is just algebra; the line never changes.\n\nMicro: slope 3 through (2, 5): y − 5 = 3(x − 2) → y = 3x − 1.' },
  { skillId: 'm-ineq2d', title: 'Two-variable inequalities', card: 'y > mx + b describes a REGION: the boundary line plus a side. Dashed line for strict (< or >), solid for ≤ or ≥. Pick the side by testing one easy point — (0,0) unless the line passes through it. A system of inequalities keeps only where ALL the shaded regions overlap.\n\nMicro: is (0,0) in y < 2x + 3? Test: 0 < 3 ✓ — shade the origin side.' },
  { skillId: 'm-functions', title: 'Functions', card: 'A function is an input→output rule: each input gets exactly ONE output. f(3) means "the output at input 3" — notation, not multiplication.\n\nMicro: f(x) = x² − 1 → f(−2) = 3.' },
  { skillId: 'm-piecewise', title: 'Piecewise & absolute-value functions', card: 'A piecewise function uses different rules on different input intervals. Decide which interval contains the input BEFORE calculating. Absolute value is piecewise distance: |x| = x for x ≥ 0 and −x for x < 0.\n\nMicro: if f(x)=2x for x≤3 and x² otherwise, f(4)=**16**.' },
  { skillId: 'm-polys', title: 'Polynomials & factoring', card: 'Expanding multiplies every term by every term; factoring runs it backward. For x² + bx + c: find two numbers with product c, sum b. Verify by re-expanding — factoring has a built-in answer check.\n\nMicro: x² − x − 6 = (x − 3)(x + 2).' },
  { skillId: 'm-quadratic', title: 'Intro quadratics', card: 'Quadratics can have two solutions. Solve x² = k by ±√k; solve factorable ones by setting = 0 and using the zero-product property: a product is 0 only when a factor is 0.\n\nMicro: (x−3)(x+2) = 0 → x = 3 or **−2**.' },
  { skillId: 'm-radicals', title: 'Radicals & rational exponents', card: 'A fractional exponent records a root and a power: x^(m/n) = (ⁿ√x)^m. Simplify radicals by pulling out perfect-power factors, and keep exact forms when decimals would hide structure.\n\nMicro: √72 = √(36·2) = **6√2**.' },
  { skillId: 'm-exponential', title: 'Exponential growth & decay', card: 'Linear change adds the same amount; exponential change multiplies by the same **factor**. A rate r becomes factor 1+r for growth or 1−r for decay, so repeated change is A(1+r)^t.\n\nMicro: 200 growing 10% twice → 200(1.1)² = **242**, not 240.' },
  { skillId: 'm-polyadvanced', title: 'Advanced polynomial structure', card: 'Zeros, factors, and division are one story: p(a)=0 exactly when x−a is a factor, and p(a) is the remainder when dividing by x−a. Multiplicity controls whether a graph crosses or touches at a zero.\n\nMicro: p(2)=0 → **x−2 is a factor**.' },
  { skillId: 'm-rationalfunc', title: 'Rational expressions & functions', card: 'A rational function is a polynomial ratio. Restrictions come from the ORIGINAL denominator, even after factors cancel. Leading terms control end behavior; uncanceled denominator zeros create vertical asymptotes.\n\nMicro: (x−3)(x+1)/(x−3)=x+1, but **x≠3**.' },
  { skillId: 'm-radicaleq', title: 'Radical & rational equations', card: 'Record domain restrictions first, isolate the radical or denominator, then use inverse operations. Squaring and clearing denominators can create candidates that were never valid, so every result must be checked in the original equation.\n\nMicro: √x = −2 has **no real solution**, even though squaring suggests x=4.' },
  { skillId: 'm-logarithms', title: 'Logarithms', card: 'A logarithm asks for an exponent: log_b(a)=c means b^c=a. Product, quotient, and power log rules are exponent rules read backward, and logs solve equations whose unknown sits in an exponent.\n\nMicro: log₂(32)=**5** because 2⁵=32.' },
  { skillId: 'm-complex', title: 'Complex numbers', card: 'i is defined by i²=−1. Combine real parts with real parts and imaginary parts with imaginary parts; when multiplying, distribute and replace every i² with −1.\n\nMicro: (2+i)(2−i)=4−i²=**5**.' },
  // ---- math: geometry
  { skillId: 'm-angles', title: 'Angles & parallel lines', card: 'Straight line = 180°, right angle = 90°, triangle sum = 180°, vertical angles equal. Parallel lines + transversal: corresponding and alternate angles are equal; co-interior sum to 180°. Every angle chase is these five facts chained.\n\nMicro: angles 62° and x on a straight line → x = 118°.' },
  { skillId: 'm-geoconstruct', title: 'Geometric construction & slicing', card: 'Construction data may determine one figure, several, or none. For three sides, the two shorter must add to more than the longest. A cross-section is the flat shape where a plane cuts a solid.\n\nMicro: sides 3, 4, 8 make **no triangle** because 3+4≤8.' },
  { skillId: 'm-triangles', title: 'Pythagorean theorem', card: 'In a RIGHT triangle, legs² sum to hypotenuse²: a² + b² = c², with c always facing the right angle. Finding a leg rearranges: leg² = c² − a². Real-world use begins with spotting the right angle in the situation.\n\nMicro: legs 6, 8 → hypotenuse **10**.' },
  { skillId: 'm-transform', title: 'Transformations & similarity', card: 'Slides add to coordinates; reflections flip one sign (across x-axis: negate y). Similar figures share ONE scale factor for all lengths — find it from any matching pair, then apply everywhere.\n\nMicro: scale 12/8 = 1.5 → a 6 becomes 9.' },
  { skillId: 'm-congruence', title: 'Congruence, constructions & proof', card: 'Rigid motions preserve distance and angle, so they prove congruence. Triangle criteria such as SSS, SAS, ASA/AAS, and HL name enough information to force one size and shape; SSA usually does not.\n\nMicro: two sides plus their included equal angle → **SAS**.' },
  { skillId: 'm-nonrighttrig', title: 'Trigonometry in general triangles', card: 'Use the Law of Sines when you know an opposite side-angle pair; use the Law of Cosines for SAS or SSS information. The cosine law becomes Pythagorean at 90°.\n\nMicro: c²=a²+b²−2ab cos C.' },
  { skillId: 'm-trigfunctions', title: 'Trigonometric functions', card: 'On the unit circle, a point at angle θ is (cos θ, sin θ). This defines trig for every angle. In y=M+A sin(2πt/P), M is the midline, |A| the amplitude, and P the period.\n\nMicro: at 90°, (cos θ, sin θ)=**(0,1)**.' },
  { skillId: 'm-area', title: 'Area & perimeter', card: 'Area counts unit squares (rect: l·w; triangle: half its rectangle). Perimeter walks the boundary. Composite shapes: split into knowns, or subtract the hole from the whole — then check with the other method.\n\nMicro: L-shape = big rectangle − missing corner.' },
  { skillId: 'm-circles', title: 'Circles', card: 'π is not magic — it IS the ratio circumference/diameter (≈3.14). So C = πd, and A = πr² (squared radius!). Sanity bracket: area sits between the inner square 2r² and outer square 4r².\n\nMicro: r = 5 → C ≈ 31.4, A ≈ 78.5.' },
  { skillId: 'm-volume', title: 'Volume & surface area', card: 'Prisms and cylinders share one law: V = base area × height (stacked layers). Surface area sums the faces — sketch the net when in doubt.\n\nMicro: cylinder r=3, h=10 → V = π·9·10 ≈ 283.' },
  { skillId: 'm-circleproof', title: 'Circle theorems', card: 'An inscribed angle is half its intercepted arc; a radius meets a tangent at 90°. Chord, secant, and tangent relationships turn circle geometry into triangle similarity and products of segment lengths.\n\nMicro: a 100° arc makes a **50° inscribed angle**.' },
  { skillId: 'm-coordinategeometry', title: 'Coordinate geometry & proof', card: 'Coordinates turn geometric claims into checkable algebra. Equal slopes prove parallel lines, negative-reciprocal slopes prove perpendicular lines, matching midpoints prove bisection, and distance formulas prove equal lengths.\n\nMicro: slopes 2 and −1/2 prove a **right angle**.' },
  { skillId: 'm-solidgeometry', title: 'Geometric measurement & solids', card: 'Volume compares layers: prisms and cylinders use Bh; pyramids and cones use one third of Bh; spheres use 4πr³/3. Cross-sections and rotations explain how two-dimensional measurements build three-dimensional solids.\n\nMicro: same base and height → cone volume is **one third** of its cylinder.' },
  { skillId: 'm-conics', title: 'Conic sections', card: 'Circle form (x−h)²+(y−k)²=r² exposes center and radius. Parabola form (x−h)²=4p(y−k) exposes vertex, focus, and directrix. These equations encode geometric distance definitions.\n\nMicro: (x−2)²+(y+1)²=9 has center (2,−1), radius **3**.' },
  { skillId: 'm-model', title: 'Mathematical modeling', card: 'Modeling = choosing the equation shape that matches how the situation GROWS: equal amounts per step → linear; equal fractions per step → exponential; through-zero rate → proportional. Then test the model at its edges (x = 0, one step).\n\nMicro: "loses 5% of current charge hourly" → exponential.' },
  { skillId: 'm-proof', title: 'Proof & counterexample', card: 'A "for all" claim needs a reason covering every case (write odd as 2k+1 and compute); ONE counterexample kills it. Hunt counterexamples where behavior changes: 0, 1, negatives, fractions between 0 and 1.\n\nMicro: "squares are bigger than their roots" dies at 1/4.' },
  { skillId: 'm-nonroutine', title: 'Non-routine problem solving', card: 'When no method is apparent: work backward from the goal, try small cases and hunt the pattern\'s STRUCTURE, draw the situation, or name the unknown and translate. The meta-skill is switching representations deliberately, not grinding one.\n\nMicro: "steps back to 8" puzzles → invert the steps, reverse the order.' },
  // ---- physics
  { skillId: 'p-measure', title: 'Measurement & units', card: 'SI base habits: meters, kilograms, seconds. Carry units through every calculation — they multiply and cancel like numbers, and a wrong-unit result is a wrong result caught early.\n\nMicro: m/s × s = m ✓.' },
  { skillId: 'p-motion', title: 'Speed & velocity', card: 'Speed = distance/time. Velocity adds DIRECTION: a lap around the track has speed but zero average velocity (no net displacement). d = v·t rearranges to whichever unknown you need.\n\nMicro: 120 m in 30 s → 4 m/s.' },
  { skillId: 'p-graphs', title: 'Motion graphs', card: 'On a position-time graph, SLOPE is speed: steep = fast, flat = stopped, downhill = returning. Average speed = total distance / total time — not the average of segment speeds (they lasted different times).\n\nMicro: flat segment ≠ no data; it means parked.' },
  { skillId: 'p-accel', title: 'Acceleration', card: 'Acceleration = change in velocity / time (m/s each second). v = v₀ + at builds speed step by step. Deceleration is just negative a.\n\nMicro: 0 → 12 m/s in 4 s → a = 3 m/s².' },
  { skillId: 'p-forces', title: 'Forces & Newton\'s laws', card: 'Only the NET force matters: F = ma. Balanced forces → a = 0 → velocity stays AS IS (moving or not — motion needs no push, changing motion does). List forces with directions before computing.\n\nMicro: 50 N push − 20 N friction on 10 kg → a = 3 m/s².' },
  { skillId: 'p-energy', title: 'Work & energy', card: 'Work = force × distance along the motion; energy is the capacity it buys. KE = ½mv² — the SQUARE means doubling speed quadruples energy. Energy transforms and transfers; totals balance.\n\nMicro: 20 N over 5 m = 100 J.' },
  { skillId: 'p-momentum', title: 'Momentum', card: 'p = mv — motion\'s "quantity", combining mass and velocity. In collisions the total is conserved: what one object loses, the other gains.\n\nMicro: 5 kg at 4 m/s carries 20 kg·m/s.' },
  { skillId: 'p-density', title: 'Density & pressure', card: 'Density ρ = m/V: how much stuff per space. Less dense than the surrounding fluid → floats. Pressure = force/area: the same push hurts more through a smaller area.\n\nMicro: 200 g in 250 cm³ → 0.8 g/cm³ → floats in water.' },
  { skillId: 'p-circuits', title: 'Simple circuits', card: 'V = IR: voltage pushes, resistance resists, current results. In series, resistances add and the same current flows through everything.\n\nMicro: 12 V across 6 Ω → 2 A.' },
  { skillId: 'p-estimate', title: 'Orders of magnitude', card: 'Estimate in powers of ten anchored to things you know cold (you ≈ 1.7 m, a liter of water = 1 kg, walking ≈ 1.5 m/s). A computed answer in the wrong power of ten is wrong regardless of the algebra.\n\nMicro: seconds/day ≈ 9 × 10⁴.' },
  { skillId: 'p-waves', title: 'Waves & sound', card: 'Wave speed links frequency and wavelength: **v = fλ**. In one medium speed is usually fixed, so raising frequency shortens wavelength. Amplitude tracks energy/intensity, not pitch.\n\nMicro: 300 m/s ÷ 100 Hz = **3 m** wavelength.' },
  // ---- coding
  { skillId: 'c-vars', title: 'Variables & expressions', card: 'A variable is a labeled box; assignment (=) REPLACES its contents, reading the right side first with current values. Trace line by line — code runs in order, each line seeing all previous effects.\n\nMicro: x = 3; x = x + 2 → the box now holds 5.' },
  { skillId: 'c-bool', title: 'Booleans & conditionals', card: 'Comparisons produce true/false; && needs both, || needs one. if/else-if chains stop at the FIRST true branch — order is logic. % gives remainders: n % 2 === 0 detects even.\n\nMicro: 17 % 5 = 2.' },
  { skillId: 'c-loops', title: 'Loops', card: 'A loop is repetition with a changing state. Trace with a table: one row per pass, columns for each variable. Boundary discipline: does the last value run? Does the first?\n\nMicro: for(i=1;i<=3;i++) runs i = 1, 2, 3 — three passes.' },
  { skillId: 'c-funcs', title: 'Functions', card: 'A function packages steps behind a name: arguments in, return value out. Parameters are LOCAL copies — the caller\'s variables are untouched (for numbers). Returned values are values: they can feed the next call.\n\nMicro: f(f(2)) evaluates inside-out.' },
  { skillId: 'c-arrays', title: 'Arrays & state', card: 'Arrays index from **0**; the last item is a[a.length − 1]. Loops + arrays = scan patterns: accumulate a total, track a best-so-far, count matches. Name what the tracker variable MEANS.\n\nMicro: a = [4,7,2] → a[1] is 7.' },
  { skillId: 'c-trace', title: 'Tracing & debugging', card: 'Debugging is hypothesis testing: predict what each line should do, observe what it does, and the first divergence is the bug\'s address. The size of the error often fingerprints the cause (off by one element? by one order of magnitude?).\n\nMicro: expected 25, got 22, missing element = 3 → the loop skipped a value worth 3.' },
  { skillId: 'c-algo', title: 'Search & sort concepts', card: 'Sorted data lets each comparison discard HALF the candidates (binary search: ~log₂ n steps). Unsorted forces linear scans. The lesson generalizes: exploit structure; do not average over it.\n\nMicro: 1000 names → 10 halvings.' },
  { skillId: 'c-decomp', title: 'Decomposition & invariants', card: 'Split problems where pieces can be understood and tested ALONE. An invariant is a sentence that stays true every loop pass ("the prefix is sorted so far") — it is how you KNOW a loop is right without simulating every input.\n\nMicro: testable piece: average([2,4]) must be 3.' },
  { skillId: 'c-complexity', title: 'Algorithmic complexity', card: 'Complexity asks how work grows when input grows. One pass is linear O(n); halve the search space each step and it is logarithmic O(log n); compare every pair and it is quadratic O(n²). Constants matter in practice, but growth dominates at scale.\n\nMicro: doubling n doubles a scan but roughly quadruples a nested pair-check.' },
  // ---- science reasoning
  { skillId: 's-hypo', title: 'Hypotheses & controls', card: 'A fair test changes ONE variable and holds the rest; the control group is the baseline that gives the comparison meaning. Claims must stay inside what was tested: which subjects, how long, compared to what.\n\nMicro: two plants, same light/water/soil, only music differs.' },
  { skillId: 's-measure', title: 'Measurement error', card: 'Every measurement wobbles — that is why we repeat. A tight cluster = reliable process; an outlier WITH a known cause may be excluded, openly. One reading is an anecdote.\n\nMicro: 21, 22, 21, 22, 35(phone buzzed) → average the four.' },
  { skillId: 's-corr', title: 'Correlation vs causation', card: 'A link has three suspects: A causes B, B causes A, or hidden C causes both. Ask "what kind of person/place/time produces both at once?" — then name the comparison that would separate the stories.\n\nMicro: ice cream & pool accidents → summer.' },
  { skillId: 's-design', title: 'Experimental design', card: 'A causal test needs comparable groups. **Random assignment** balances hidden differences on average; blinding blocks expectation effects; replication tests whether the result survives new samples. Random sampling helps represent a population—it is not the same job as random assignment.\n\nMicro: assign volunteers by lottery, keep treatment labels hidden, repeat.' },
  { skillId: 's-graphs', title: 'Graph & claim evaluation', card: 'The two classic chart tricks: a truncated axis (small change fills the frame) and a cherry-picked window (one rising segment "proves" a trend). Defense: reconstruct the honest numbers and the full series before believing any shape.\n\nMicro: 91k → 99k is +9%, however tall the bars look.' },
  { skillId: 's-fermi', title: 'Fermi estimation', card: 'Break the unknown into factors you can roughly estimate, multiply, and own the roughness (within ~2× is success). Note which factor you trust least — that is where better data goes first.\n\nMicro: school-year class minutes ≈ 180 × 6 × 60 ≈ 65,000.' },
  { skillId: 's-sources', title: 'Source quality & stats traps', card: 'Rank evidence by controlled comparisons × independent replications − conflicts of interest. Traps to name on sight: relative risk on a tiny base, percentage POINTS vs percent, survivorship (who is missing from the data?), volunteer samples.\n\nMicro: "risk doubles!" from 1 to 2 in 10,000.' },
  // ---- labs
  { skillId: 'o-obsinf', title: 'Observation vs inference', card: 'Three levels: OBSERVED (you can point to it), INFERRED (strongly supported, still a step beyond), UNKNOWN (several stories fit equally). Most reasoning errors are inferences smuggled in as observations.' },
  { skillId: 'o-recall', title: 'Scene recall', card: 'Memory keeps what encoding stored — so encode deliberately: sweep in one spatial order, verbalize exact numbers and words, expect a "what was absent?" question. Familiarity is not memory.' },
  { skillId: 'o-listen', title: 'Listening & paraphrase', card: 'A good paraphrase compresses without adding, resolving, or judging — the speaker could answer "yes, exactly." Preserve stated ambivalence ("fair, BUT three weeks") — flattening it is how listening fails.' },
  { skillId: 'o-bias', title: 'Bias & calibration', card: 'Cold reading runs on Barnum statements (true of everyone), rainbow ruses (trait AND its opposite), and feedback fishing (your own facts mirrored back). Defense: ask "what fraction of ALL people fits this?" and track who introduced each fact.' },
  { skillId: 'o-memory', title: 'Memory techniques', card: 'The method of loci stores items as vivid images along a route you know; spatial memory does the holding. It reliably boosts list/order recall — a real skill, not a general-IQ device. Interactive, absurd images stick; static ones fade.' },
  { skillId: 'i-logic', title: 'Deduction', card: 'Valid = IF the premises are true the conclusion cannot be false — form, not content. The reliable moves: chains (A→B→C) and contrapositive (no B → no A). The classic traps: affirming the consequent, converse errors.' },
  { skillId: 'i-bayes', title: 'Base rates & updating', card: 'Convert to natural frequencies: out of 1000, how many ARE the thing? How many flag? Count true flags and false flags, then divide. Low base rates drown good tests in false positives — P(A|B) ≠ P(B|A).' },
  { skillId: 'i-hypo', title: 'Competing hypotheses', card: 'Hold several explanations; choose the TEST whose possible results split them. A test that comes out the same under every hypothesis teaches nothing. Falsifying checks beat confirming ones.' },
  { skillId: 'i-abduce', title: 'Best explanation', card: 'Two steps. FIRST generate several explanations — the commonest failure is only ever having one. THEN rank them: which covers ALL the evidence (scope), and which needs the fewest unsupported extras (parsimony)? Detail is a cost, not evidence.\n\nCeiling: best available is not proven. Name the leading candidate, the gap, and the test that would close it.' },
  { skillId: 'i-forecast', title: 'Forecasting', card: 'A forecast is a probability you can be scored on (Brier = (p − outcome)²; lower is better). Calibration means your 70%s come true about 70% of the time. Update on evidence; log the update.' },
  { skillId: 'i-game', title: 'Games & cooperation', card: 'Check payoff tables column by column for dominant choices — do not assume betrayal pays. Repetition + memory create the shadow of the future, which is why reputation and fairness are strategically sound.' },
  { skillId: 'i-equilibrium', title: 'Best response & equilibrium', card: 'A **best response** answers one question: given what the OTHER side does, which row (or column) pays me most? Mark the best reply in every column, then in every row. A cell marked by both is a **Nash equilibrium** — neither side can improve by moving alone.\n\nThe surprise: an equilibrium can be bad for everyone. Stability means "no one gains by deviating **alone**", not "this is the best outcome available".\n\nMicro: if 2 beats 1 in both of my columns, that row is dominant — play it, and expect the other side to reason the same way about their own.' },
  { skillId: 'i-commit', title: 'Commitment & bargaining', card: 'Sometimes **removing your own options wins**. A promise you cannot break is believable; one you can back out of is not. Burning a bridge, publishing a price, or handing a decision to a rule all work by making a threat or offer credible.\n\nRepetition changes everything: in a one-shot game defection can pay, but when the same people meet again the future payoff of being trusted outweighs one betrayal. That is why reputation is strategy, not sentiment.\n\nMicro: "I\'ll match any lower price" removes your freedom to discount quietly — and that is exactly why rivals believe it.' },
  { skillId: 'st-decomp', title: 'Backward planning', card: 'Start at the goal and ask "what must be true just before this?" until you reach today. Anchor fixed events first, pour flexible tasks around them, and split the splittable.' },
  { skillId: 'st-ev', title: 'Decision trees', card: 'Weigh risky options by probability × payoff — then check the GOAL: a needed threshold can overrule the average. EV describes the long run; single shots may punish the "right" choice.' },
  { skillId: 'st-premortem', title: 'Pre-mortems', card: 'Assume the plan already failed and explain why — prospective hindsight surfaces risks plain listing misses. The usual killers are boring: no start trigger, no slack, no owner, resources assumed.' },
  { skillId: 'st-estimate', title: 'Estimation', card: 'Your past actuals outrank tonight\'s optimism (the planning fallacy is a feeling). Outside view first: what did similar tasks take? Apply your known correction factor, and log predictions to learn it.' },
  { skillId: 'st-ethics', title: 'Ethical strategy', card: 'Test any strategy with the daylight question: would it still work if everyone saw it? Wins that degrade the decision (deception, exclusion, attrition) sell reputation — the compounding asset — for one result.' },
  { skillId: 'h-emotion', title: 'Perspective-taking', card: 'Big moments carry blended feelings — name both parts. Behavior readings are hypotheses, not mind-reading: the move after a reading is a question. The vivid self-centered story is usually about your attention, not their mind.' },
  { skillId: 'h-influence', title: 'Influence defense', card: 'The three levers: time pressure, social pressure, emotional debt. Ask what the message PREVENTS (thinking, checking, comparing). Naming the tactic collapses most of its power. Urgency + secrecy + credentials = phishing, always.' },
  { skillId: 'h-boundary', title: 'Boundaries & de-escalation', card: 'A boundary = your limit + what you will do — no insult, no essay. De-escalate by dropping volume, validating the feeling, and steering to specifics or exit. Safety issues skip peer-handling: bring in a trusted adult.' },
  { skillId: 'x-learn', title: 'Study science', card: 'Highest-utility techniques by the evidence: practice TESTING and SPACING. Rereading and highlighting feel smooth and build little. Interleave once basics exist — choosing the method is part of the skill. (Sources: research ledger.)' },
  { skillId: 'x-method', title: 'Strategy recognition', card: 'On mixed tests, the hard step is rarely the algebra — it is NAMING which method the problem wants. Train it directly: read a problem, identify the structural cue ("percent of what base?", "two unknowns, two facts"), name the method, and only then (elsewhere) solve. Cue-spotting is what interleaved practice builds.' },
  { skillId: 'x-calib', title: 'Self-calibration', card: 'Track confidence against outcomes; the gap has a direction (over/under). High-confidence errors are gold — they mark beliefs needing repair. "I don\'t know" stated honestly beats a confident guess.' },
  { skillId: 'x-explain', title: 'Explanation & compression', card: 'Compress a concept to one sentence, one example, one NON-example, one trap. The non-example does the most work: boundaries define concepts. A sentence you cannot finish marks a gap worth studying.' },
  { skillId: 'x-focus', title: 'Focus & error diagnosis', card: 'Design beats discipline: one named objective, phone elsewhere, distraction list for stray thoughts, defined end. File errors by CAUSE (concept / strategy / slip / misread) — the cause picks the cure.' },
  { skillId: 'x-stuck', title: 'Working while stuck', card: 'Two different states wear the same feeling. PRODUCTIVE STRUGGLE: you are still generating attempts and each one rules something out — keep going, this is what learning a new idea feels like from the inside. GENUINELY STUCK: you have repeated the same move twice with no new information — that is a signal, not a verdict. Then ask for the SMALLEST next thing (one hint, one worked step, one definition), never the answer; state what you know and what is blocking. Both avoiding help and leaning on it are ways of not learning.' },
  { skillId: 'x-compare', title: 'Two cases, one structure', card: 'Reading one worked example teaches you that example. Reading TWO that look nothing alike and writing down what they SHARE builds something portable, because the only thing the two have in common is the structure. Do it in this order: strip the names and the setting, say what each side wanted, then name what made the same move work in both.\n\nMicro: flatmates trading chores and two clubs sharing a room are the same problem — unequal priorities, so trade whole issues instead of halving each one.' },
  { skillId: 'x-transfer', title: 'Noticing when a method applies', card: 'Knowing a method and noticing it applies are two different abilities, and only the second one travels. Most remindings arrive by SURFACE — the last problem about ladders, not the last problem with a right angle — so a method you own sits unused when the cover story changes. The move: cross out every name, place and subject, then describe what is left. Two problems match when those noun-free descriptions match.\n\nMicro: "two taps fill a tank" and "two proofreaders share a job" are the same problem; "a hose fills a pool in 25 minutes" is not, though it is about water.' },
  { skillId: 'x-interleave', title: 'Mixing practice on purpose', card: 'Practice that jumps between problem types feels worse and usually works better, because a block hands you the method before you read the question and a mixed test does not. Mixing trains **choosing** the method, not executing it — so it pays when the types are easy to confuse and the test is delayed and mixed. It does not always pay: blocked practice can win on an immediate same-type test, and while a method is brand new, seeing examples together is what builds the category.\n\nMicro: one classroom study found a delayed test at **72%** after mixed practice against **38%** after blocked — but the day you first meet a method, block it.' },
  { skillId: 'x-desirable', title: 'Difficulty that helps', card: 'Some effort builds memory and some just costs time, and they feel the same while you are doing them. Harder-now-better-later means retrieval, spacing, generating before being told, and mixing confusable types. Just-harder means a noisy room, a broken tool, unreadable notes, studying exhausted — real effort that never lands on the material. Easier-and-worse means rereading and highlighting, which mostly produce a feeling of knowing. Difficulty is never useful **because** it is difficult.\n\nMicro: rereading until it all feels familiar rates 9/10 and recalls little; a blank-page attempt that goes half wrong rates 5/10 and recalls more — confidence during study is a poor guide to next week.' },
  // ---- observer: what is not in front of you
  { skillId: 'o-selection', title: 'Who is missing from the data', card: 'Before reading any group of responses, ask what had to happen for someone to appear in it. Reviewers are people who stayed; survey replies come from people who answered; a forum of founders is missing everyone whose business closed. When the filter is linked to the outcome being asked about, the pattern shows up whether or not the claim is true — which makes it worse than a small sample, not a version of one.\n\nMicro: an app rated 4.8 by 900 reviewers, where most installs are abandoned in eleven days, tells you about the people who stayed.' },
  { skillId: 'o-expect', title: 'What would I see if it were false?', card: 'Evidence only counts when it could have come out differently. A statement that fits every person, or a test that would have looked the same under the opposite theory, has told you nothing however satisfying it feels. The move is to state in advance what the world would look like if the claim were WRONG, then check which world you are in.\n\nMicro: "you can be outgoing but also value your own company" fits nearly everyone, so agreeing with it is not evidence about you.' },
  { skillId: 'o-anchor', title: 'First numbers and first impressions', card: 'An opening figure quietly sets the range everyone then argues inside, even when it is arbitrary. Adjusting from it feels like reasoning and mostly is not, because the adjustment starts from the anchor. The defence is to produce your OWN number first — from a reference class, or from a floor you can compute — and only then look at theirs.\n\nMicro: "was 80, now 55" makes 55 feel like the answer; the question is what it is worth, which 80 was never evidence about.' },
  { skillId: 'o-frame', title: 'Same fact, different framing', card: 'One fact can be stated as a gain or a loss, a survival rate or a mortality rate, ninety per cent fat free or ten per cent fat. The arithmetic is identical and the reaction is not. Restate any claim in its opposite frame and see whether your reaction survives; if it flips, the frame was doing the work.\n\nMicro: 96% survival and 4% mortality are the same number, and people choose differently between them.' },
  { skillId: 'o-claimtype', title: 'Fact, judgement, or guess', card: 'Three different things arrive in the same paragraph and in the same confident tone. A FACT was measured or stated directly. A REASONED JUDGEMENT is a conclusion the findings support. SPECULATION goes past what was collected. Sorting them is not pedantry — most weak arguments work by moving a guess into the fact column while nobody is looking.\n\nMicro: "the sample warmed by 4 degrees" is a fact; "the reaction is exothermic" is a judgement; "this could power a home" is speculation.' },
  // ---- investigator: numbers under uncertainty
  { skillId: 'i-natfreq', title: 'Counting people, not percentages', card: 'Rewrite every probability question as counts out of a whole group and the hard ones stop being hard. Start with a round number of people, split them by the base rate, then split each part by the test result. The answer is a ratio of two counts you can point at. Do NOT reach for a formula — the counting version is the one that is still there weeks later.\n\nMicro: of 1000 people, 10 are ill and 9 test positive; of the 990 well, 99 test positive. So a positive test means 9 out of 108.' },
  { skillId: 'i-refclass', title: 'Reference classes & the outside view', card: 'Before reasoning about THIS case, ask how similar cases actually turned out. Building an estimate from the steps of the job in front of you misses everything that is not a step — the interruptions, the rework, the waiting — and the record of similar jobs already contains those. Start from the distribution, then adjust for the few genuine differences.\n\nMicro: eleven essays took 7-11 hours each, so the twelfth is not a four-hour essay however carefully the four hours were itemised.' },
  { skillId: 'i-samplesize', title: 'How much a sample can tell you', card: 'Small samples swing wildly, and they swing in BOTH directions — which is why tiny groups top and bottom league tables at once. Averages settle down as the sample grows, roughly with the square root: four times the data halves the wobble. Before calling a difference a finding, ask how big a difference this many observations would produce by luck alone.\n\nMicro: a 4-patient clinic hits 100% success far more often than a 400-patient one, and it means less.' },
  { skillId: 'i-diagnostic', title: 'How much this evidence moves things', card: 'Evidence is strong when it is much likelier under one explanation than the others, and worthless when both explanations predict it equally — however dramatic it is. The question is never "does this fit my theory" but "how much better does it fit mine than the rival". Look for the observation the two explanations DISAGREE about.\n\nMicro: a wet pavement fits both "it rained" and "the cleaner came"; a wet pavement under one parked car fits only one of them.' },
  { skillId: 'i-conditional', title: 'If-then and what follows', card: 'From "if P then Q" only two moves are valid: P is true so Q is true, and Q is false so P is false. The two tempting ones are not: Q is true says nothing about P, and P is false says nothing about Q. Testing a rule means hunting for the case that would BREAK it, which is the P-true case and the Q-false case, never the comfortable ones.\n\nMicro: "if it is raining the ground is wet" — a wet ground does not mean rain.' },
  { skillId: 'i-fallacy', title: 'Named ways an argument breaks', card: 'A closed list beats a vague sense that something is off, because naming the fault tells you what to ask for next. The common ones: assuming what you are proving, offering two options when more exist, attacking the person, treating a sequence as a cause, generalising from a handful, answering an argument nobody made, sliding between two meanings of a word, and treating popularity as proof.\n\nMicro: "everyone knows it works" is not evidence it works, only that it is believed.' },
  // ---- strategist: choosing under constraint
  { skillId: 'st-tradeoff', title: 'Trade-offs & dominated options', card: 'Two moves, in order. First DROP anything worse on every criterion — a dominated option needs no weighing at all. Then, when priorities across issues are unequal, trade whole issues instead of halving each one: each side takes all of what it cares about most and gives away all of what it cares about least, and both do better on the same total.\n\nMicro: splitting every chore evenly gives everyone half a job they hate; swapping whole jobs costs the same and suits both.' },
  { skillId: 'st-reversible', title: 'Reversibility & keeping options', card: 'A cheap mistake you can undo is worth more than a careful one you cannot. Before an irreversible step, ask what the smallest test is that would settle the question, and find the point of no return in the plan so you know which decisions deserve the care. Speed is safe exactly where reversal is cheap.\n\nMicro: trying a subject for a term is recoverable; dropping the prerequisite that gates it is not.' },
  { skillId: 'st-secondorder', title: 'And then what happens?', card: 'A plan changes what people do, and what they do next is often the thing that decides whether it worked. Follow it one more step: who now has a reason to behave differently, and does that undo the goal or merely cost something? Rules that measure a proxy are the classic case — the proxy improves and the thing it stood for does not.\n\nMicro: rewarding bugs found produces more bugs found, and not necessarily fewer bugs.' },
  { skillId: 'st-sunk', title: 'What is already spent', card: 'Money and hours already gone cannot be recovered by continuing, so they are not part of the decision. Compare only what it costs FROM HERE against what it is worth from here. Note the honest half of this: sometimes finishing really is right, and when it is, it is because the remaining cost is worth the remaining benefit — never because of what was already paid.\n\nMicro: two hours into a bad film, the question is whether the next hour is worth it, not the two.' },
  // ---- insight: reading situations honestly
  { skillId: 'h-attribution', title: 'Situation or person?', card: 'We explain our own behaviour by circumstances and other people\'s by character, and the second explanation arrives first and feels obvious. Before settling on "they are like that", ask what the situation was and what fact would tell the two readings apart. This is for correcting your OWN reading, not for diagnosing anyone.\n\nMicro: someone is short with you — late, hungry, and worried looks the same from outside as rude.' },
  { skillId: 'h-projection', title: 'Assuming they see it as you do', card: 'Your own view feels like the ordinary one, so people routinely overestimate how many others share it. A plan that only works if everyone thinks like the planner will not survive contact. The move is cheap: ask instead of assume, and treat your own preference as one data point rather than the baseline.\n\nMicro: picking the restaurant you would want is not the same as picking the one most people would want.' },
  { skillId: 'h-interests', title: 'The interest under the position', card: 'What someone demands and what they need are different things, and only one of them is negotiable. A position is a single solution they have already chosen; the interest is what that solution was supposed to get them. Ask what the demand is FOR, and options usually appear that satisfy both sides without either getting their stated position.\n\nMicro: "I need the window open" is a position; "I am too warm" is the interest, and a fan also solves it.' },
  { skillId: 'h-repair', title: 'Repair after it goes wrong', card: 'An apology that works names the specific harm, takes responsibility without an excuse attached, and says what will be different. The failures are recognisable: centring your own feelings, "if you were hurt", explaining until the explanation becomes a defence, and asking for forgiveness on the spot. Repair is offered, not owed on demand — the other person decides when they are ready.\n\nMicro: "I am sorry I read your message and did not reply for a week; I will tell you when I am slow" beats "sorry you felt ignored".' },
  // ---- investigator: game theory, part two
  { skillId: 'i-iterated', title: 'Cross out, then look again', card: 'An option is DOMINATED when another beats it in every case — not merely on average. You can drop it without knowing anything about what the other side will do, which is what makes it worth spotting. The second pass is the part people miss: once they can see you would never play it, those outcomes stop existing for them too, and something of theirs may now be dominated that was not before.\n\nMicro: announcing that a slot is impossible for you helps the group eliminate, where ranking it last leaves it alive.' },
  { skillId: 'i-backward', title: 'Start at the end', card: 'When somebody moves after you, you are not choosing between your options — you are choosing between their replies. So solve the LAST move first, using their payoffs and not yours, then work backwards. Picking the branch with the biggest number for you assumes they will act against their own interest to put it there.\n\nMicro: if you already know the answer to an argument, the argument is not the decision — the answer is.' },
  { skillId: 'i-selection', title: 'Why winning can be bad news', card: 'Take several honest, unbiased guesses at an unknown value and pick the highest one: it is too high, and nobody made a mistake. That is why the winner of an auction has usually overpaid — they won by being the most over-optimistic, not the most accurate. The general form: whenever you got something because you were the keenest, ask what the people who passed could see.\n\nMicro: the only applicant for an easy job, the only person who thinks a deal is good, the seller who is very willing.' },
  { skillId: 'i-common', title: 'Do they know that you know?', card: '"Everyone knows" and "everyone knows that everyone knows" are different things, and acting together needs the second. Told separately, two people each hold the plan and neither can rely on it. Told together, each can see the other got it. That is why announcements are made in front of everybody rather than passed along one at a time, and why saying an unpopular thing out loud changes a room that already agreed privately.\n\nMicro: "did you get my message?" is not a redundant question.' },
  { skillId: 'i-unpredict', title: 'When a pattern is the loss', card: 'A pattern is only a weakness when somebody can act on it against you — two tests: is anyone choosing a move in response to yours, and does their choice change how you do? Where both hold, being readable IS the loss, whatever your skill. And you cannot generate randomness by trying: people alternate far too much, so a real coin\'s long runs are exactly the tell. Use an outside source.\n\nMicro: most routines have no opponent, and unpredictability costs you reliability with the people on your side.' },
  { skillId: 'i-commons', title: 'Sensible each time, ruinous together', card: 'When the gain is private and the cost is shared, every individual choice can be correct while the total is ruinous — no greed required, just arithmetic. So the fix is never "be more considerate", which leaves every incentive where it was. It is changing what each person chooses between: a named share, an agreed cap, a trigger rule, or a count everyone can see. Visibility works because restraint stops being a gift to whoever does not restrain.\n\nMicro: a shared fridge with named shelves stops being a commons.' },
  // ---- insight: other minds, honestly
  { skillId: 'h-mindread', title: 'How good is your read?', card: 'Imagining someone else\'s point of view makes you more confident without making you more accurate — across 25 experiments, including ones with real couples and close friends, it did not improve accuracy and sometimes made it worse. Asking did. So treat the certainty that grows while you sit and think as information about the thinking, not about the person: no new evidence arrived. Separate what you saw from what you supplied, and keep the second half labelled.\n\nMicro: a story about someone that gets more convincing the longer you turn it over has not gained any evidence since you started.' },
  { skillId: 'h-nested', title: 'What they think you think', card: 'People act on what they believe, and beliefs come from what actually reached them — not from what is true, and not from what you know. Track exposure in order: who was told, who saw, who was in the room but missed it. A belief about a belief stacks the same rule twice. This is a logic form, close cousin to nested conditionals, and getting good at it makes you better at the puzzle rather than better at people.\n\nMicro: a message being sent is not a message being received, and nobody is told when an email bounces.' },
  { skillId: 'h-asking', title: 'Asking instead of guessing', card: 'Getting the information beats generating it — but only when the question is genuinely answerable. A question with your conclusion inside it collects agreement, not information. Name the specific thing, admit your own uncertainty out loud, and make the answer you least want to hear an easy one to give. When asking is not available, the honest position is an unresolved read, which is different from quietly picking one.\n\nMicro: "was that aimed at me? I couldn\'t tell" gets an answer; "you weren\'t having a go at me, were you?" gets a no.' },
  // ---- puzzle: search & structure
  { skillId: 'z-invariant', title: 'Invariants & parity', card: 'Find the quantity that never changes, and a whole class of attempts is ruled out at once without trying any of them. If every legal move preserves a total, a remainder or a colour count, then any target with a different value is unreachable — that is a proof, not a failure to find the answer.\n\nMicro: a knight always moves light square to dark, so it can never return to its start in an odd number of moves.' },
  { skillId: 'z-search', title: 'Systematic search & pruning', card: 'Order the possibilities so that checking one kills many. A question that splits the remaining candidates in half is worth far more than one that eliminates a single case, and the worst case is what to plan for — not the lucky case. Guessing and restarting feels faster and covers less.\n\nMicro: 64 possibilities need only 6 halving questions, and up to 63 one-at-a-time ones.' },
  { skillId: 'z-extremal', title: 'Start from the extreme case', card: 'The largest, smallest, first or last element is usually the most constrained, so it is the one that is forced — and once it is placed, it forces others. Starting in the middle keeps every option open and gets you nowhere. Pigeonhole reasoning is the same idea: with more items than boxes, some box is forced.\n\nMicro: 13 people means two share a birth month, whoever they are.' },
  { skillId: 'z-sequence', title: 'Patterns & sequences', card: 'Find the rule that generates the run, then CHECK it against a term you did not use to find it. Fitting the data you already had is not evidence — two different rules routinely agree on the first three terms and part company on the fourth. When two rules both fit, the useful question is which extra term would tell them apart.\n\nMicro: 1, 2, 4 fits doubling and also fits "add 1, add 2, add 3" — the next term is 8 or 7.' },
  { skillId: 'z-chess', title: 'Chess tactics', card: 'Candidate discipline: list EVERY check and capture before evaluating any. For each, name the opponent\'s best reply. Recount defenders as if pinned pieces were absent. Chess trains chess — the CHECKLIST is what transfers, and only if practiced elsewhere.' },
  { skillId: 'z-spatial', title: 'Spatial assembly', card: 'Most-constrained first: corners and pockets admit the fewest pieces. Commit awkward shapes early; keep flexible ones in reserve. Rotate mentally before placing.' },
  { skillId: 'z-deduce', title: 'Constraint deduction', card: 'Process clue types in order of hardness: direct facts, links, orderings, negatives. For any stuck value, list who could still hold it — act on the shortest list. Case-testing to contradiction is proof, not guessing.' },
]

export const KB_BY_SKILL: Map<string, KbCard> = new Map(KB_CARDS.map((c) => [c.skillId, c]))

/** Simple token search over the knowledge base (Coach screen). */
export function searchKb(query: string, limit = 6): KbCard[] {
  const tokens = query.toLowerCase().split(/\s+/).filter((t) => t.length >= 2)
  if (!tokens.length) return []
  const scored = KB_CARDS.map((c) => {
    const hay = (c.title + ' ' + c.card + ' ' + c.skillId).toLowerCase()
    let score = 0
    for (const t of tokens) {
      if (c.title.toLowerCase().includes(t)) score += 3
      else if (hay.includes(t)) score += 1
    }
    return { c, score }
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
  return scored.slice(0, limit).map((x) => x.c)
}
